### ISSUE TITLE
Built-in support for stem blocks

### ISSUE THREAD

**Issue by paulvickers** [asciidoctor/asciidoctor-epub3#10]
I'm using Asciidoctor to convert a programming text book from print to electronic format. Therefore, I need epub, mobi, and PDF to be able to handle math expressions.

Please can you add stem support to asciidoctor-epub3?

**Comment by paulvickers** [comment]
Does this work yet? If so, what are the exact steps needed?

**Comment by paulvickers** [comment]
I've been trying to follow all the threads and *think* that the solution is now to use asciimath which will render as mathml in HTML, epub, and pdf.

However, I cannot get it to work in epub3 or pdf.

I have installed the asciimath gem, and an adoc file containing the following:

    [asciimath]
    ++++
    k_{n+1} = n^2 + k_n^2 - k_{n-1}
    ++++
    
    [asciimath]
    ++++
    sqrt(4) = 2
    ++++
    
    stem:[sqrt(4) = 2]
    
    \$sqrt(4) = 2\$

it all renders fine in HTML with the following command: `asciidoctor -a stem sample.adoc`

However, if I try using the pdf or epub 3 backends:

    asciidoctor -a stem -r asciidoctor-epub3  -b epub3 sample.adoc
    asciidoctor -a stem -r asciidoctor-pdf  -b pdf sample.adoc

I get the following error:
    asciidoctor: WARNING: conversion missing in backend pdf for stem

I am running asciidoctor v 1.5.4.

**Comment by mojavelinux** [comment]
@paulvickers are you using asciidoctor-mathematical as described in https://github.com/asciidoctor/asciidoctor-pdf/issues/45. (Alternatively, you can use the [mathoid treeprocessor](https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/mathoid-treeprocessor/extension.rb)). If loaded correctly, the extension should be replacing stem nodes with image nodes. That way, the converter never even sees the stem nodes.

The fact that Asciidoctor is complaining about the missing conversion for stem tells me you aren't using either the asciidoctor-mathematical or mathoid-treeprocessor extensions. Right now, using an extension is the only approach for converting stem blocks that works in both Asciidoctor PDF and EPUB3.

I know it's frustrating that we don't have an official solution for this yet. We're going to get there. There's just a lot to do right now.

**Comment by paulvickers** [comment]
@mojavelinux: here's what happens with both. First, trying to use mathoid:

    asciidoctor -a stem -r asciidoctor-epub3 -r./lib/httlap-blocks -r ./lib/mathoid-treeprocessor.rb -b epub3 sample.adoc

Result:

    asciidoctor: FAILED: /Volumes/SSD Disk/git Repos/test/sample.adoc: Failed to load AsciiDoc document - asciidoctor: FAILED: /Volumes/SSD Disk/git Repos/test/content.adoc: Failed to load AsciiDoc document - Failed to open TCP connection to localhost:16000 (Connection refused - connect(2) for "localhost" port 16000)

Trying to use AD-mathematical:

    asciidoctor -a stem -r asciidoctor-epub3 -r./lib/httlap-blocks -r asciidoctor-mathematical -b epub3 sample.adoc

Result:

    conversion missing in epub3 backend for stem
    conversion missing in epub3 backend for stem

I have attached the spine and content files (I've appended a .txt extension to allow me to attach them).
[content.adoc.txt](https://github.com/asciidoctor/asciidoctor-epub3/files/416511/content.adoc.txt)

[sample.adoc.txt](https://github.com/asciidoctor/asciidoctor-epub3/files/416510/sample.adoc.txt)

**Comment by mojavelinux** [comment]
The problem is that none of the stem instances in your sample are handled by the extension. Asciidoctor Mathematical only processes latexmath stem blocks. In your example, you have two AsciiMath stem blocks and one inline stem expression.

Here's a content.adoc that will work:

```
[latexmath]
++++
k_{n+1} = n^2 + k_n^2 - k_{n-1}
++++

[latexmath]
++++
\sqrt(4) = 2
++++
```

asciidoctor-mathematical is calculating the image target path incorrectly so it fails to embed when using Asciidoctor PDF unless you set the `imagesoutdir` attribute to `.`. This is a known issue. See https://github.com/tstumm/asciidoctor-mathematical/issues/8.

**Comment by mojavelinux** [comment]
> First, trying to use mathoid:

The mathoid extension requires some extra setup that is documented here: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/mathoid-treeprocessor/setup.sh. However, I haven't tested it recently. It is definitely still lab material :)

**Comment by paulvickers** [comment]
D'oh! `[latexmath]` it is. This then has the unfortunate result of super jumbo sized equations in the epub3 output. Seems like asciidoctor-mathematical isn't the all round performer I need it to be. I want to generate HTML, pdf, epub, and Kindle mobi with some mathematical content in all versions. At this point I'm tempted just to render all the equations as pngs myself and embed them as images. Grrrr....

Therefore, I tried the mathoid-treeprocessor route again but still can't get it to work. 

1. `setup.sh` seems to be out of date. I replaced the link to the wikimedia git repo with 

    git clone -b integration --recursive https://github.com/mojavelinux/mathoid

which makes that bit of the script not fall over *and* provides a mathoid folder with `main.js`/

I have manually installed `npm`, `librsvg` (via Homebrew), and `phantomjs` as the setup.sh was throwing errors. Now it runs without comment.

The next bit in `setup.sh` says:

    # Make sure you can run the following command:
    #
    # cd mathoid
    # phantomjs main.js
    #
    # Then visit the following URL in your browser:
    #
    # http://localhost:16000/?q=x^2&type=asciimath
    #
    # You should see x to the power of 2 rendered.


The browser session using `http://localhost:16000/?q=x^2&type=asciimath` gives the error:

    This page contains the following errors:
    
    error on line 1 at column 1252: Attribute xlink:href redefined
    Below is a rendering of the page up to the first error.

(there is nothing after that).

When I go to my test project and run:

    asciidoctor  -r asciidoctor-epub3 -r mathoid-treeprocessor -b epub3 sample.adoc

I get the error

    paulvickers@PaulVickerssPro test $ asciidoctor  -r asciidoctor-epub3 -r mathoid-treeprocessor -b epub3 sample.adoc --trace
    /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mathoid-treeprocessor (LoadError)
    	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	    from /usr/local/bin/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/options.rb:219:in `block in parse!'
	    from /usr/local/bin/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/options.rb:217:in `each'
	    from /usr/local/bin/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/options.rb:217:in `parse!'
	    from /usr/local/bin/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/options.rb:33:in `parse!'
	    from /usr/local/bin/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:21:in `initialize'
	    from /usr/local/bin/gems/asciidoctor-1.5.4/bin/asciidoctor:12:in `new'
	    from /usr/local/bin/gems/asciidoctor-1.5.4/bin/asciidoctor:12:in `<top (required)>'
	    from /usr/local/bin/asciidoctor:22:in `load'
	    from /usr/local/bin/asciidoctor:22:in `<main>'

Is this a problem with my ruby installation, or a problem with mathoid? I'm puzzled by the reference to `site_ruby` as the ruby that gets executed at the command line is the one installed by homebrew.

**Comment by paulvickers** [comment]
UPDATE: *facepalm*

Checked Activity Monitor which showed an orphaned phantomjs process running. Killed that and ran again and got a pdf as output but with no math in it. Using the test.adoc from the extensionslab repo:

    = _Precompiled_ Math!
    
    [stem#equation1]
    ++++
    "d"(bbp,bbq) = sqrt((p_1 - q_1)^2 + (p_2 - q_2)^2)
    ++++

Compile with 

    asciidoctor  -r asciidoctor-pdf -r ./lib/mathoid-treeprocessor  -b pdf test.adoc --trace

Get the following output:

    asciidoctor: WARNING: could not embed image: /Volumes/SSD Disk/git Repos/test/equation1.svg; Duplicate attribute "xlink:href"
    Line: 23
    Position: 7155
    Last 80 unconsumed characters:

The generated svg file is not an equation but text containing an error message "This page contains the following errors..."

**Comment by mojavelinux** [comment]
>  Seems like asciidoctor-mathematical isn't the all round performer I need it to be. I want to generate HTML, pdf, epub, and Kindle mobi with some mathematical content in all versions. At this point I'm tempted just to render all the equations as pngs myself and embed them as images. 

That's why the mathoid processor is such an all-around champion.

I'll have a look at the mathoid processor and see if I can bring it up to date. That should hopefully help move things along. Stay tuned.

**Comment by paulvickers** [comment]
> I'll have a look at the mathoid processor and see if I can bring it up to date. That should hopefully help move things along. Stay tuned.

That'll be great, thanks! Any idea what's causing the epub3 backend to throw the `to_ios` error?

**Comment by mojavelinux** [comment]
> Any idea what's causing the epub3 backend to throw the to_ios error?

9/10 it's not adhering the the project structure requirements describe at https://github.com/asciidoctor/asciidoctor-epub3#declaring-the-spine

**Comment by paulvickers** [comment]
Hmmm.... Okay, thought I'd already got that covered. I did realise that some of the declarations were before the book title, so here's the revised spine:

    = TEST
    Paul Vickers
    v1.0, 2014-04-15
    :doctype: book
    :producer: Asciidoctor
    :keywords: Asciidoctor, samples, e-book, EPUB3, KF8, MOBI, Asciidoctor.js
    :copyright: CC-BY-SA 3.0
    :icons: font
    :imagesdir: Images
    :stem:
    
    include::content.adoc[]

And here's the content.adoc

    Here is some maths in a block
     
    [asciimath]
    ++++
    k_{n+1} = n^2 + k_n^2 - k_{n-1}
    ++++
    
    And another block.
    [asciimath]
    ++++
    sqrt(4) = 2
    ++++
    
    Here is some inline maths asciimath:[a=4^2].

The command: `asciidoctor  -r asciidoctor-epub3 -r ./lib/mathoid-treeprocessor -b epub3 sample.adoc --trace` executes without errors now. But here's the output:

![epubtree1](https://cloud.githubusercontent.com/assets/4840626/17697893/939599ce-63af-11e6-86aa-36972070a306.png)

![epubtree2](https://cloud.githubusercontent.com/assets/4840626/17697896/98dc4afe-63af-11e6-9a2c-8a69bbdfc617.png)

I notice though in https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/71#issuecomment-240054559 that the whole mathoid architecture has changed. Mine is still using phantomJs so I'll take a look at the newer version now.

**Comment by mojavelinux** [comment]
Asciidoctor EPUB3 currently requires the imagesdir attribute to be images
(all lowercase).

Even then, we'll need to make sure the images make it into the correct
directory for use with the EPUB3 converter. I checked PDF, but not EPUB3
yet.

**Comment by paulvickers** [comment]
With the `:imagesdir:` variable correctly set:

![mathoidtreeproc3](https://cloud.githubusercontent.com/assets/4840626/17705124/2d35c44a-63cf-11e6-83fe-1869eba1fc95.png)

The stem blocks are huge, and the inline still not being rendered as math.

**Comment by mojavelinux** [comment]
:+1: 

The sizing is the next step. Right now, the images will expand to the space they are given. We can allow a width attribute to be defined on the stem block, then pass that to the image block that the extension creates.

It's true that inline stem macros are not yet supported. The challenge here is that Asciidoctor doesn't provide a way to hook into inline nodes in a Treeprocessor yet. We'll have to take a different approach, perhaps by extending the converter.

**Comment by slonopotamus** [comment]
https://github.com/fabmen/asciidoctor-epub3/commit/95addc15f501dea3ec70b53ef8aedf31e4254311 has some code using AsciiMath to convert stem blocks to MathML, possibly we should use it.

**Comment by slonopotamus** [comment]
Okay, it's finally time to fix this six-year-old issue. #346 adds support for MathML blocks. It doesn't handle inline stems (yet), I plan to add that soon.
