### ISSUE TITLE
producing a guide list in package.opf

### ISSUE THREAD

**Issue by gambhiro** [asciidoctor/asciidoctor-epub3#116]
Producing a `<guide>` list in `package.opf` would be good. [Here there is a good description][guide] of it and the semantic types that can be marked with it.

[guide]: http://epubsecrets.com/where-do-you-start-an-epub-and-what-is-the-guide-section-of-the-opf-file.php

In particular this is useful to define the opening page of the ebook, i.e. the first page which the reader sees when opening the book for the first time.

It engages the reader sooner when the ebook opens at the first chapter or the title page just before that, instead of putting them through a chore of paging through front matter pages (dedication, abbreviations, foreword, preface).

The `<guide>` should be composed of the include file list, with optional `:type:` attributes declared for the items.

Consider the following example:

cthulhu.adoc

``` asciidoc
= The Call of Cthulhu
H.P. Lovecraft
:doctype: book
:creator: {author}

include::foreword.adoc[]

include::01-the-horror.adoc[]

include::02-the-tale.adoc[]
```

foreword.adoc

``` asciidoc
:type: foreword

= Foreword

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

01-the-horror.adoc

``` asciidoc
:type: text

= The Horror in Clay

The most merciful thing in the world, I think, ...
```

02-the-tale.adoc

``` asciidoc
= The Tale of Inspector Legrasse

The older matters which had made the sculptor's dream...
```

Which should have the following `package.opf`:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<package ...>
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    ...
  </metadata>
  <manifest>
    ...
    <item id="item_foreword" href="foreword.xhtml" media-type="application/xhtml+xml"/>
    <item id="item_the-horror-in-clay" href="the-horror-in-clay.xhtml" media-type="application/xhtml+xml"/>
    <item id="item_the-tale-of-inspector-legrasse" href="the-tale-of-inspector-legrasse.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine>
    <itemref idref="item_foreword"/>
    <itemref idref="item_the-horror-in-clay"/>
    <itemref idref="item_the-tale-of-inspector-legrasse"/>
  </spine>
  <guide>
    <reference type="foreword" title="Foreword" href="foreword.xhtml"/>
    <reference type="text" title="The Horror in Clay" href="the-horror-in-clay.xhtml"/>
    <reference title="The Tale of Inspector Legrasse" href="the-tale-of-inspector-legrasse.xhtml"/>
  </guide>
</package>
```

**Comment by gambhiro** [comment]
One idea I had for this is that the chapter heading could have an attribute that marks this.

```
[#chapter-one, opening-page]
= Chapter One
```

Then, when constructing the `<guide>` items for the OPF, the file containing that chapter could be identified, and receive a `type="text"`.

Do you think that would work?

**Comment by gambhiro** [comment]
I was looking at `packager.rb` and `spine_item_processor.rb` and it seems to me I should be able to do this, but I am confused about the different abstractions here.

So either recognizing an attribute on the chapter title:

```
[#the-horror-in-clay, opening-page]
= The Horror in Clay

The most merciful thing in the world, I think, ...
```

Or recognizing an attribute in the chapter document:

```
:opening-page:

[#the-horror-in-clay]
= The Horror in Clay

The most merciful thing in the world, I think, ...
```

I don't see how the spine items get their (xml) attributes in the OPF file.

Which of these would make sense, in terms of how the document objects are processed?

For example, putting a conditional somewhere around [spine_item_processor.rb#L41](https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/spine_item_processor.rb#L41) such as:

```
if spine_item_doc_meta.attr? 'opening-page'
```

**Comment by gambhiro** [comment]
Oh well. I gave up and wrote a helper script which changes the line in `package.opf` with `sed`.

Nevertheless, I still believe this would be a good feature to have in the tool.

**Comment by gambhiro** [comment]
Renamed this issue and added a better description.

**Comment by slonopotamus** [comment]
We're not going to do this since [`guide` element is deprecated](http://idpf.org/epub/301/spec/epub-publications.html#sec-guide-elem).
