### ISSUE TITLE
parsing table frame and grid attributes

### ISSUE THREAD

**Issue by gambhiro** [asciidoctor/asciidoctor-epub3#117]
A table's grid and frame attributes are not recognized:

```
[%autowidth, grid=none, frame=none]
|===
| AN    | Aṅguttara Nikāya
| Cv    | Cullavagga
| Dhp   | Dhammapada
|===
```

**Comment by mojavelinux** [comment]
I think you're saying that the "none" value is not respected. Is that correct?

**Comment by gambhiro** [comment]
Yes, "none" certainly didn't work (default "topbot" and "rows" were used instead).
