### ISSUE TITLE
<b> tags around words in chapter subtitle

### ISSUE THREAD

**Issue by gambhiro** [asciidoctor/asciidoctor-epub3#123]
I would like to start a discussion on the chapter header's html structure. This is currently:

``` html
<header>
  <div class="chapter-header">
    <p class="byline">
      <img src="images/avatars/default.jpg"/>
      <b class="author">Dan Allen</b>
    </p>
    <h1 class="chapter-title">
      Asciidoctor EPUB3
      <small class="subtitle">
        <b>A</b> <b>native</b> <b>EPUB3</b> <b>converter</b> <b>for</b> <b>AsciiDoc</b>
      </small>
    </h1>
  </div>
</header>
```

Particular questions:

What is the motivation for breaking the subtitle into words and wrapping them in `<b>`?

For example I wanted a `text-align: center` title, but the text can't be centered while wrapped in an inline tag. For now all I could do is to make a local copy of `asciidoctor-epub3` where I removed the `<b>` from the template string.

Would a `<span>` be perhaps better than `<small>` for the subtitle tag?

The idea is that `<span>` would be more neutral. The concern here is that if a custom CSS (fonts, extra styling) doesn't work on a particular device, or only some of it does, then the result can be strange, depending on how the device will interpret `<small>`.

**Comment by mojavelinux** [comment]
It's important to understand that a lot of the HTML and CSS was chosen to work around bugs in the various readers. So the question is usually, "what bug were you working around when you decided to do x?" Because, trust me, I wouldn't have done some of the things I did if the readers were conforming ;)

I would love to use `<span>` more often, but I choose `<b>` because I needed it to be styled when CSS was disabled. But it's been so long that I'm starting to forget some of the reasons for the hacks.

> What is the motivation for breaking the subtitle into words and wrapping them in <b>?

I was either for kerning or text transform. I can't remember which. You'd have to check the git history to see what I wrote when I committed it.

> Would a `<span>` be perhaps better than `<small>` for the subtitle tag?

Actually, this one is a best practice. I've read many articles that agree that a subtitle should be done using `<small>`. But, of course, there's always a heated debate over this stuff.

**Comment by mojavelinux** [comment]
I remember why I used the `<b>` elements. At the time (maybe still) kindlegen removes `<span>` elements. So if you don't use an element it doesn't strip, there is no way to apply CSS to the text. I came up with `<b>` as a workaround in a pinch.

**Comment by mojavelinux** [comment]
kindlegen murders documents.

**Comment by gambhiro** [comment]
Thanks, I thought there must have been reasons.

So as I understand what you are saying, the `<b>` is for controlling inter-word distance.

Thinking of this from another perspective, what do you think of moving these templated pieces into one `page.xhtml.erb`?

It would allow a feature where the user can use an attribute to specify a custom template.

Also, it would be easier to track down what goes on to construct the page. It is easy to get lost among the string templates while trying to keep in mind the whole picture.

**Comment by mojavelinux** [comment]
> So as I understand what you are saying, the <b> is for controlling inter-word distance.

Was. It may not be needed anymore. I'm definitely to let it go if we can't justify keeping it.

**Comment by mojavelinux** [comment]
> It would allow a feature where the user can use an attribute to specify a custom template.

That's already possible, unless you mean doing it at a finer-grained level (well, and actually testing it too, which is something we really need). The template system built into core always overrides the handlers provided by the converters.

**Comment by mojavelinux** [comment]
> It is easy to get lost among the string templates while trying to keep in mind the whole picture.

The string templates are really meant to be something that is behind the scene...a (hand) compiled version of the core functionality. We definitely want to promote and encourage overriding via templates, as that's a core design in the processor. But what's really missing here are tests to verify that we haven't inadvertently closed that door in anyway...and of course some docs to show how it's done.

**Comment by mojavelinux** [comment]
In other words, the built-in templates were always meant to be overridden. They are just there to provide the foundation.

**Comment by gambhiro** [comment]
Excellent notes, thank you.

I'm voting for the `<b>` to go, PR #125.

**Comment by gambhiro** [comment]
When you have some time, please describe an example of how to override the built-in templates.

I saw that asciidoctor talks about overriding them as tilt templates, but beyond that I was lost on how to go about doing it.

**Comment by mojavelinux** [comment]
I looked a little closer into why the `<b>` was there and I now see another reason. The `<b>` is also being used to change the line height in Kindle. By default, Kindle does not allow the line height to be adjusted. But if you float the elements, then the line height disappears and can be restored manually using margins.

We may decide trying to control this is still wrong. But that at least explains why it was done.

**Comment by slonopotamus** [comment]
I don't see any difference between these. Ufortunately, I don't have a hardware Kindle to test on it.

![image](https://user-images.githubusercontent.com/92637/73911769-d9e97600-48c3-11ea-9398-caa33e530f28.png)

**Comment by slonopotamus** [comment]
So, I do agree that `<b>` is a hack and should be avoided if possible, but I also would like to be able to control line-height for better visuals. If we find other way to do that, I'll happily get rid of `<b>`.

**Comment by gambhiro** [comment]
Thank you for thinking about it long and hard, perhaps it's time for me to learn to like it :)

**Comment by mojavelinux** [comment]
@gambhiro I don't think that's what @slonopotamus was saying. I think he was saying he's trying to figure out how to get rid of the `<b>` without impacting the line height.

**Comment by slonopotamus** [comment]
Exactly. No need to close this issue. I just need to do some experiments.

**Comment by slonopotamus** [comment]
So.

1. Seems like it is really impossible to make line-height smaller than 1.2em on Kindle.
2. I discovered that it is possible to insert HTML inside section title, for example:

```adoc
== [[surprise]]title
```

Regex-based `<b>` code is not handling this properly and damages markup.
