### ISSUE TITLE
The error "ERROR: front cover image not found or readable" points to the wrong path

### ISSUE THREAD

**Issue by emmanuelrosa** [asciidoctor/asciidoctor-epub3#124]
In the `packager.rb` [this](https://github.com/asciidoctor/asciidoctor-epub3/blob/255db56c5e302051307f17f418968c0188e204e1/lib/asciidoctor-epub3/packager.rb#L138) line generates an error when the provided front cover image cannot be read. The problem is the path shown in the error is not the one being tested for readability. Here's a copy of the code in question:

```
if ::File.readable?(::File.join workdir, image_path)
        unless !image_attrs.empty? && (width = image_attrs['width']) && (height = image_attrs['height'])
          width, height = 1050, 1600
        end
      else
        warn %(asciidoctor: ERROR: front cover image not found or readable: #{image_path})
        image_path = nil
      end
end
```

Notice that the `readable?` predicate is being applied to the `workdir` joined to `image_path`, yet the error only displays the `image_path`.

In my case, `image_path` is an absolute path (and the file exists) but I don't know what `workdir` is being set to, making the error misleading.

**Comment by mojavelinux** [comment]
I see the problem. There are actually two issues here. First, it doesn't show the full path of the image, but it also doesn't show which file is referencing it.

I think the original goal of the message was to show the path of the image as it appears in the document. However, without context, this is only marginally useful. It's also not consistent with the other converters. So I'll update it to show the document that references it and the full path to the missing file. With that information, it shouldn't be hard to find where to fix it (working within the constraints we currently have).

**Comment by mojavelinux** [comment]
Thanks for reporting!
