### ISSUE TITLE
don't insert quotation marks

### ISSUE THREAD

**Issue by gambhiro** [asciidoctor/asciidoctor-epub3#129]
I would like to recommend not inserting additional quotation marks for quote blocks.

The formatting of quotations is the task of the author and the editors. They will have a house style for quotation formatting (who is indented, who is wrapped in quote marks, etc.) and they apply that in the manuscript. If they don't put quotation marks around a quote, they don't want them there.

The ebook tool should not interfere with this.

In addition, hiding it in the CSS with `display: none` causes kindlegen to error out:

```
Error(parsing):E3013: More number of characters are hidden using display:none than allowed limit. Limit: 10000 in file: ...
```

**Comment by agoncal** [comment]
I am also rewriting the existing CSS to get rid of the quote. I am using the same css code mentioned by @gambhiro 

``` 
blockquote span.close-quote:not(:empty) {
    display: none;
}
```

**Comment by gdamore** [comment]
Your approach is cleaner.  I wound up using a passthrough with my own HTML to generate a my desired format.  (I didn't want the block quote either, although to be fair I was trying to abuse the block quote style to format something that wasn't a  quote at all but rather a dedication.)

**Comment by lulalala** [comment]
Another reason this might be preferred is that in east Asian character sets, the quotation marks are 「」『』.
