### ISSUE TITLE
Converter crashes if safe mode is >= server

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-epub3#13]
The EPUB3 converter crashes if the safe mode is >= server because it cannot resolve the 'docdir' attribute to a directory (because it's empty).

```
lib/asciidoctor-epub3/packager.rb:180:in `add_profile_images'
```

**Comment by slonopotamus** [comment]
This is no logner true since

```
commit 6e460d39d465ffc4a9a71830b3ec19400bf42321
Author: Dan Allen <dan.j.allen@gmail.com>
Date:   Sun Aug 17 04:56:02 2014 -0600

    don't attempt to chdir to DATA_DIR; use full path

    - fixes failure when gem is located inside a JAR
    - also resolve docdir to '.' when empty to avoid file resolution problem
```

I don't say that we work properly under server/secure mode (we don't). There are bunch of errors like images attempted to resolve against wrong dir, failed includes in secure mode (obviously). But no, it doesn't crash.
