### ISSUE TITLE
Font Awesome not supported on Kindle

### ISSUE THREAD

**Issue by agoncal** [asciidoctor/asciidoctor-epub3#131]
Asciidoctor provides [Font Awesome for admonition icons](https://github.com/asciidoctor/asciidoctor/issues/115), which is great. So if you add the following in your document : 

```
[NOTE]
====
This is a note, blah, blah, blah.
====
``` 

It displays nicely an icon on HTML, PDF, EPUB, and after conversion to a MOBI file with `kindlegen`, it also displays a nice icon on the Kindle Previewer.... but not on the Kindle device itself (instead it shows a funny symbol with a question mark). [Reading the KDP forum](https://kdp.amazon.com/community/message.jspa?messageID=1023297) I discovered that it is not possible to display Font Awesome on the device.

One alternative would be to use an image. But I would lose the nice indentation of the note and so one:

```
image::note.png[]

This is a note, blah, blah, blah.
``` 

I know you can [customize the CSS](https://github.com/asciidoctor/asciidoctor-epub3/issues/41) for an EPUB, could that be an option ? Or is there another way to display NOTE, TIP, IMPORTANT, CAUTION, WARNING symbols on a Kindle ?

**Comment by mojavelinux** [comment]
How are you getting the file to the Kindle device? I ask because if you are using "Send to Kindle", stripping fonts is a known "feature" of that program. If you load it onto the device either using a direct transfer or by way of the Kindle store, the fonts are preserved and the icons will appear.

See https://github.com/asciidoctor/asciidoctor-epub3#send-to-kindle.

**Comment by agoncal** [comment]
Whouah !!! Document transformation is really a dark art ! 

I've transferered the mobi file with a USB cable, and the icon appears.

Thanks @mojavelinux

**Comment by mojavelinux** [comment]
Trust me, I know. I've visited some very dark corners of these caverns.
