### ISSUE TITLE
github.com/bitcoinbook/bitcoinbook doesn't compile

### ISSUE THREAD

**Issue by varung** [asciidoctor/asciidoctor-epub3#134]
I tried to use ascidoctor-epub3 to compile https://github.com/bitcoinbook/bitcoinbook/
However, it complained about many errors, and the resulting epub has "untitled" instead of proper chapter names.
Can you recommend how to compile that book into an epub?
using asciidoctor directly seems to work and produce a nice looking html, albeit without any table of contents

**Comment by mojavelinux** [comment]
Does the book follow the structure rules documented here?

https://github.com/asciidoctor/asciidoctor-epub3#structuring-your-manuscript

**Comment by ysb33r** [comment]
I had a quick look and it would definitely need some conditional sections to make it work for epub.

**Comment by varung** [comment]
Hm. How do the authors compile it then? If you look in the themes folder,
they have one called ePub, so the authors are definitely compiling it into
ePub. Is it possible they've omitted needed files?

**Comment by mojavelinux** [comment]
This sounds like an issue you need to enable in that repository, not in this one. That's a question for them.

**Comment by slonopotamus** [comment]
[They say](https://github.com/bitcoinbook/bitcoinbook/issues/369#issuecomment-327332853) they're using [O'Reilly Atlas](https://atlas.oreilly.com/).

The only thing we can do here is do add +1 vote for #47. Until then, asciidoctor-epub3 requires a specific document structure to work. Closing.
