### ISSUE TITLE
Honor ID on admonitions

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor-epub3#146]
Ids are not retained on admonitions.

```
[[note_xref]]
[NOTE]
.Title of the note
====
Block of text.
====
```

**Comment by jnavila** [comment]
@mojavelinux Looking at the code, I guess most blocks don't comply with IDs. Maybe a generic solution would be great on this part. I don't know enough of ruby to start directly a fix. Do you have a path to a solution and do you think it can be handled by someone else?

**Comment by mojavelinux** [comment]
We'll just need to take it one node at a time. When I created the EPUB3 converter, I must not have needed the IDs for the project I was using it for. But they should definitely be supported.

To learn what I'm changing, just study the PRs. I'll send one shortly for this issue.
