### ISSUE TITLE
Revisit SVG-based scaling for cover image

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-epub3#147]
It has been reported that some readers have problems displaying the cover image due to the SVG scaling that we use. In some cases, the cover doesn't display with Aldiko (format: jpg, size: 1121x1600) and crashes UB Reader. In other readers, the book cover doesn't show up in the bookshelf (Kobo Aura 20).

If we find the SVG-based scaling is still desirable for some users, we should put it behind an AsciiDoc attribute so it can be turned off. If we find we don't need it at all, then we can just replace it with a `<figure>` element.

**Comment by slonopotamus** [comment]
We need to recheck status of this in modern era. @mojavelinux what's UB Reader at all? I see [traces over internets](https://ub-reader.jaleco.com/android) that it _was_ a reader app for Android but seems like it is no longer available via Google Play.

**Comment by mojavelinux** [comment]
I believe it's this one: https://ub-reader.en.softonic.com/android

Unless you have someone reporting issues about it, I would ignore it.

**Comment by slonopotamus** [comment]
That's exactly the same thing I've linked :) Okay, let's close this until someone complains.
