### ISSUE TITLE
Including an attribute file causes "Untitled" chapter in TOC

### ISSUE THREAD

**Issue by huanlin** [asciidoctor/asciidoctor-epub3#151]
My "spine" file looks like below:

```
include::_links.adoc[]

include::preface.adoc[]

include::chapter1.adoc[]
```

In which _links.adoc simply contains some links, like:

```
:link-google: https://www.google.com/[Google]
:link-author-blog: http://my-blog.com/[Author Blog]
```

the epub file generated by asciidoctor-epub3 shows an "Untitled" chapter in the table of content.

![image](https://user-images.githubusercontent.com/605065/34107769-5abb327a-e438-11e7-80af-a60aabc04e9f.png)

If I remove the line `include::chapter1.adoc[]` and copy those attributes to the spine file, then the "Untitled" issue is gone.

Does that mean I can't have attribute files included from the spine file? (asciidoctor-pdf works fine)

I'm using Asciidoctor EPUB3 1.5.0.alpha.7 with Asciidoctor 1.5.6.1.
Runtime Environment: ruby 2.3.3p222 (2016-11-21 revision 56859)

**Comment by slonopotamus** [comment]
I believe this issue will be automagically fixed when we implement #47.
