### ISSUE TITLE
Sony readers crash

### ISSUE THREAD

**Issue by roskenet** [asciidoctor/asciidoctor-epub3#152]
Output ePub make Sony readers (at least PRS-505 and PRS-T1) crash when opening the text after the cover image.
The reason is the padding in pre at line 923 in epub3.css.
Commented out, it shows up correctly. I don't have any idea why this simple style causes trouble for the reader and it seems to be more a bug in the reader itself than in the stylesheet.
Maybe this report is helpful for Sony PRS owners.

**Comment by mojavelinux** [comment]
This sounds to me like a bug that needs to reported with Sony. No style should be causing a reader to crash. I'm not prepared to change CSS to fix buggy software.

**Comment by crees** [comment]
Sony won't ever fix this as the reader is discontinued.  Does it make a huge difference, modifying the CSS?  It would make a huge difference to your users with Sony readers!

**Comment by mojavelinux** [comment]
I have since changed my position on this. The CSS should be as simple as possible so as to support the most readers, because trying to the readers to change is futile. If you open a new issue with information that reflects the current stylesheet, I'm sure @slonopotamus will consider it.

**Comment by slonopotamus** [comment]
I think I can get access to PRS-600.

@crees can you provide an example document that causes the crash?

**Comment by slonopotamus** [comment]
Okay, I got PRS-350 and it **does crash** when trying to open the first page of our `data\samples\sample-book.adoc`.

**Comment by slonopotamus** [comment]
For the reference, [here's problematic CSS rule](https://github.com/asciidoctor/asciidoctor-epub3/blob/v1.5.0.alpha.14/data/styles/epub3.css#L908). I suspect that @roskenet put nontrivial amounts of time into diagnosing crash down to this single CSS line.

WRT fixing it - I don't want to just remove the padding, code blocks look awful without it. Need to do some experiments, possibly will be able to find a workaround.

**Comment by mojavelinux** [comment]
I could be the units. That's just a shot in the dark, but worth checking.

**Comment by slonopotamus** [comment]
> I could be the units.

Exactly. Replaced `rem` with approximated `em` value.

![rem-em](https://user-images.githubusercontent.com/92637/75918589-11b8ee80-5e6d-11ea-97ed-d49b8dcf770d.png)

**Comment by crees** [comment]
Oh awesome, thanks both!  I'm sorry, didn't see the alert emails for replies.

**Comment by mojavelinux** [comment]
em unit could compound. It might be safer to use the equivalent pixel value (which is really all rem is, just simpler to reason about).

**Comment by slonopotamus** [comment]
Agreed, will change.
