### ISSUE TITLE
Failed to compile with lots of erros

### ISSUE THREAD

**Issue by amjadtbssm** [asciidoctor/asciidoctor-epub3#153]
I am building the Pro Git epub using the command **asciidoctor-epub3 progit.asc** but it returns error
I am new to ruby, please describe in steps to correct this issue thanks.

> asciidoctor-epub3 progit.asc
Traceback (most recent call last):
        18: from f:/Ruby25/bin/asciidoctor-epub3:23:in `<main>'
        17: from f:/Ruby25/bin/asciidoctor-epub3:23:in `load'
        16: from f:/Ruby25/lib/ruby/gems/2.5.0/gems/asciidoctor-epub3-1.5.0.alpha.7/bin/asciidoctor-epub3:4:in `<top (required)>'
        15: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        14: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        13: from f:/Ruby25/lib/ruby/gems/2.5.0/gems/asciidoctor-epub3-1.5.0.alpha.7/lib/asciidoctor-epub3.rb:3:in `<top (required)>'
        12: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        11: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        10: from f:/Ruby25/lib/ruby/gems/2.5.0/gems/gepub-0.6.9.2/lib/gepub.rb:22:in `<top (required)>'
         9: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         8: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         7: from f:/Ruby25/lib/ruby/gems/2.5.0/gems/gepub-0.6.9.2/lib/gepub/meta.rb:2:in `<top (required)>'
         6: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
         5: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
         4: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
         3: from f:/Ruby25/lib/ruby/gems/2.5.0/gems/nokogiri-1.6.6.4-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
         2: from f:/Ruby25/lib/ruby/gems/2.5.0/gems/nokogiri-1.6.6.4-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
         1: from f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
f:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)

**Comment by mojavelinux** [comment]
This looks like an error with nokogiri and Ruby 2.5. This gem hasn't yet been tested with Ruby 2.5, so I have no idea yet if it works on that version. I'm just starting to introduce 2.5 into the testing cycle for Asciidoctor.

**Comment by amjadtbssm** [comment]
Which version of Ruby is good to go with Ascii-Doctor? Do I need to downgrade ruby or install a lower version?

**Comment by amjadtbssm** [comment]
By installing Ruby 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]  from [https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.2.6.exe](https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.2.6.exe) and reinstalling all the ASCII Doctor elements using the following commands solved this issue.

First Install the Ruby from above installer (For x64 download the following [https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.2.6-x64.exe](https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.2.6-x64.exe)

First Install AsciiDoctor 
`gem install asciidoctor`

Install EPub3 gem
`gem install asciidoctor-epub3 --pre`

Install the PDF gem
`gem install asciidoctor-pdf --pre`

You can build the books now all ok :-)

If you need to use the syntax highlighting in your documents install CodeRay by using the following command

`gem install coderay`

**Comment by Almgzoub** [comment]
Thank you @amjadtbssm, your solution worked for me!

**Comment by amjadtbssm** [comment]
You are welcome @Almgzoub
