### ISSUE TITLE
Reference resolution issue with current master

### ISSUE THREAD

**Issue by deoren** [asciidoctor/asciidoctor-epub3#157]
## Problem

Somewhere between v1.5.6.1 and 752dac1b76fb376a2aa4dd20b241cc9509907e2b a regression appears to have been introduced that results in reference resolution issues.

## Example

Here is what an internal link looks like as of current master:

![now](https://user-images.githubusercontent.com/1550338/35652166-203afa3a-06a8-11e8-89b2-39152864d124.png)

Here is what the reference link looks like as of v1.5.6.1:

![before](https://user-images.githubusercontent.com/1550338/35652167-2049094a-06a8-11e8-87e5-4aed0800bc8a.png)

## How to reproduce

I have a temporary branch in my fork of the progit/progit2 repo that illustrates the problem:

https://github.com/deoren/progit2/tree/temp

Here is the Gemfile from that branch:

```
source 'https://rubygems.org'

gem 'rake'
gem 'asciidoctor', :git => 'https://github.com/asciidoctor/asciidoctor'

gem 'json'
gem 'awesome_print'

gem 'asciidoctor-epub3', :git => 'https://github.com/asciidoctor/asciidoctor-epub3'
gem 'asciidoctor-pdf', '1.5.0.alpha.16'

gem 'coderay'
gem 'pygments.rb'
gem 'thread_safe'
gem 'epubcheck'
gem 'kindlegen'
```

Once the gems are installed running `rake` will build the docs.

In case it is helpful, I have a Docker image that I can reference to automate the process of building the progit/progit2 docs and dropping them into an "output" directory within the current working directory.

## References

- test branch to repro problem: https://github.com/deoren/progit2/blob/temp
- https://github.com/asciidoctor/asciidoctor-epub3/issues/156#issuecomment-362065607
- https://github.com/progit/progit2/issues/966#issuecomment-362052242

**Comment by mojavelinux** [comment]
It's this issue that introduced the change in behavior. https://github.com/asciidoctor/asciidoctor/issues/2301

I think we just need a corresponding change to the EPUB3 converter.

**Comment by mojavelinux** [comment]
Sure enough. Asciidoctor now registers the current document in the ids table using a fallback reftext value. The EPUB3 converter should look in the (more formal) refs table first to find the document. Only if not found there should it fall back to the ids table. This change will ensure the behavior remains consistent regardless of the version of Asciidoctor core.

**Comment by mojavelinux** [comment]
Thanks for reporting!

**Comment by deoren** [comment]
> @mojavelinux: Thanks for reporting!

You are welcome, thanks for providing this software.
