### ISSUE TITLE
Green </> at the end of each chapter

### ISSUE THREAD

**Issue by agoncal** [asciidoctor/asciidoctor-epub3#163]
When converting to EPUB format, a chapter ends with the following HTML : 

```
<p class="last">This is the last sentence of a section</p>
```

This code will get rendered using the default CSS:

```
p.last::after {
  color: #57AD68;
  display: inline-block;
  font-family: "FontAwesome";
  font-size: 1em;
  content: "\f121"; /* i.e., </> */
  margin-left: 0.25em;
}
```

This will show a green `</>` at the end of each chapter. What I do is that I change the color to transparent:

```
p.last::after {
  color: rgba(255, 255, 255, 0);
  ...  
```

[I also found a blog mentioning it](https://translate.google.fr/translate?hl=en&sl=ja&u=https://backport.net/blog/2018/02/22/asciidoctor_epub3_theme/&prev=search).

Why is this character display and why it is green ? If needed, shouldn't it be transparent ?

**Comment by mojavelinux** [comment]
> Why is this character display and why it is green ?

This is a very common typographic practice to indicate the end of an article. (Browse through a stack of magazines and you'll likely to find some sort of decoration at the end of an article). It reveals the ancestry of Asciidoctor EPUB3 as a converter for creating digital magazines.

Fortunately, we now have a standard flag named publication-type to indicate what type of manuscript you are creating. I agree that this decoration should not be shown if the publication-type is book (which is now the default).

I'll send a PR that implements this proposed change.

**Comment by mojavelinux** [comment]
> What I do is that I change the color to transparent:

You could just set `display: none`.

**Comment by gdamore** [comment]
I have found that adding "<<<" to the end of the chapter content solves this.

**Comment by mojavelinux** [comment]
Yep. That works because the chapter no longer ends in a paragraph...and thus there is nothing for which the end mark to attach.
