### ISSUE TITLE
Document implicit front-matter.html feature

### ISSUE THREAD

**Issue by gdamore** [asciidoctor/asciidoctor-epub3#172]
In reading the description for #30  I discovered about the magical front-matter.html.

I wish I had known about this earlier.  I spent numerous hours trying to force the markup I needed to work properly in asciidoctor, finally settling on a passthrough except that I cannot use images there because they aren't packaged.

The existence of front-matter.html would have given me the escape I needed to have my very specially front matter pages, and saved these hours.  Documenting this will probably save someone else a lot of time too!

**Comment by mojavelinux** [comment]
You're free to take a stab at documenting it.

Also be aware that this feature will be expanding with https://github.com/asciidoctor/asciidoctor-epub3/pull/110.
