### ISSUE TITLE
Footnotes in tables produce duplicative reference IDs

### ISSUE THREAD

**Issue by aepstein** [asciidoctor/asciidoctor-epub3#173]
I have a book that contains many footnotes.  In some chapters some footnotes are in tables.  It appears that the counter used to generate unique numbering for footnotes resets within each table.  So, if I have a footnote in the body, then in the table, they are both numbered 1.  Only the latter footnote (in the table) is rendered in readers that open the book.  The document will not pass validation.

I have set up a repo to illustrate the bug here: https://github.com/aepstein/epub3-footnote-bug.

**Comment by aepstein** [comment]
@mojavelinux Any thoughts on this?

**Comment by slonopotamus** [comment]
I cannot reproduce this with current asciidoctor-epub3.

Here's generated markup from your test case:
```
<div class="footnotes">
<aside id="note-1" epub:type="footnote">
<p><sup class="noteref"><a href="#noteref-1">1</a></sup> You will not see me.</p>
</aside>
<aside id="note-2" epub:type="footnote">
<p><sup class="noteref"><a href="#noteref-2">2</a></sup> You will see me.</p>
</aside>
<aside id="note-3" epub:type="footnote">
<p><sup class="noteref"><a href="#noteref-3">3</a></sup> I am the table footnote.</p>
</aside>
</div>
```

However, while testing it, I found #295 (and already fixed it).
