### ISSUE TITLE
Feature request: Further support for document header content

### ISSUE THREAD

**Issue by Buzzardo** [asciidoctor/asciidoctor-epub3#175]
We had some content (version, copyright notice, and a legal blurb) in index-docinfo.xml. We lost all of that when we went from using Docbook in our tool chain to using purely Asciidoctor. We restored it by adding a Colophon document as the first include in the spine document. However, that forces us to have a heading. We'd like to do without that heading and have that content appear on the first page after the cover. I guess that means we want a way to insert content (that need not include a heading) onto that first page after the cover (the back of the cover, if one were to print it on both sides of the page).

**Comment by slonopotamus** [comment]
Does `front-matter.html` solve your issue? Just put it in the samr dir as book spine file and it will be inserted in the beginning of the book.

**Comment by Buzzardo** [comment]
I will experiment with that and see. Thanks.

**Comment by slonopotamus** [comment]
Oh, I didn't expect you'd answer on 1.5 year-old issue :)

There are some issues with `front-matter.html`:

* It is not documented: #172 (not fixed yet)
* It is searched in working dir instead of spine dir: #301 (fixed but not released)
* You don't get Asciidoctor markup there for obvious reasons. But possibly that's exactly what you want.

But overall it just does what I said - gets inserted as first item right after cover page.

**Comment by Buzzardo** [comment]
Because it is HTML rather than Asciidoc to be rendered, I think we are better off with the workaround we developed by using conditional statements. Thanks, though.

As for my answer on an issue from 1.5 years ago, all I can say is that it is a form of asynchronous communication. ;)

**Comment by slonopotamus** [comment]
Also note that thanks to #310 we now support Asciidoctor preamble (text between document header and first section). Also, #302 added support for preface. These two combined with front-matter.html hopefully cover all needs for various contents between cover page and main book contents.

Closing this issue, but feel free to comment if you have any more cases where this isn't enough.
