### ISSUE TITLE
Make clear asciidoctor-epub3 doesn't work under Ruby 2.5.0 (at least for now)

### ISSUE THREAD

**Issue by Almgzoub** [asciidoctor/asciidoctor-epub3#177]
Greetings,

As issue #153 indicates, newcomers do install Ruby 2.5.0 (current version), but, asciidoctor-epub3 gem will not be installed under this newer version of Ruby. it'll be labor-saving for them to state clearly in the README.adoc  file that this is a known limitation for now.

(@mojavelinux Thank you for your great work! respect :bowing_man:)

**Comment by Almgzoub** [comment]
This would be a nicer treatment. Thanks.

**Comment by discosultan** [comment]
Is there anything blocking to upgrade the nokogiri dependency?

**Comment by mojavelinux** [comment]
I think you'll find that Asciidoctor EPUB3 install just fine on Ruby 2.5. See https://travis-ci.org/asciidoctor/asciidoctor-epub3/builds/515662808

The nokogiri dependency is pulled in by gepub. So in order to upgrade it, we need to upgrade gepub. But for some reason, gepub is now 10MB!

**Comment by mojavelinux** [comment]
Regardless, I'm going to say that this issue is about upgrade gepub. That should also eliminate warnings.

**Comment by mojavelinux** [comment]
The point release of gepub (1.0.3) is now only 37 KB. If you reinstall your gems, you should get this one instead.
