### ISSUE TITLE
Unset cover, use inline links in description

### ISSUE THREAD

**Issue by MatteoCampinoti94** [asciidoctor/asciidoctor-epub3#180]
# Cover
Is there a way to not add the cover?
I'm converting some books in bulk from plain text files and I'd like for them to not have a cover "chapter" at the start of the epub. Whether the cover is set or not is not a big problem since I generate them in bulk using Calibre.

I tried `:front-cover-image!:` but that did not change anything.

I could generate the cover earlier and add it to the document, but I'd prefer to separate things.

# Description links
I'm also trying to add links to the description, but the normal syntaxes are read as is, without conversion to html.

This is the header template I'm using:
```shell
= $title
:author: $author
:toc: auto
:doctype: book
:keywords: $tags
:description: By $author_link
:front-cover-image!:

include::$file1[]

<<<

[other chapters separated by pagebreaks]
```

The $vars are the ones I use in my script, the end result looks like this:
```asciidoc
= Book Title
:author: Author
:toc: auto
:doctype: book
:keywords: tag1, tag2
:description: By https://www.example.com/author[Author]
:!front-cover-image:

include::chapter01.adoc[]

<<<
```

**Comment by slonopotamus** [comment]
@mojavelinux I want to just stop adding our default cover image. I know, it's cool and green, but no book except book about asciidoctor-epub3 itself actually wants that cover image. As a nice small bonus, this will also shave off 0.5MB from our install size.
