### ISSUE TITLE
Converting from epub to asciidoc

### ISSUE THREAD

**Issue by marmalodak** [asciidoctor/asciidoctor-epub3#181]
Converting my resume from Apple's Pages, I get errors from `asciidoctor-epub3`.

This is the output I get when I select "Embed Fonts" when exporting from Pages.

    asciidoctor-epub3 --trace -v -s jsepub.epub -o jsauto.pdf
    Traceback (most recent call last):
            11: from /mnt/myth/john/bin/asciidoctor-epub3:23:in `<main>'
            10: from /mnt/myth/john/bin/asciidoctor-epub3:23:in `load'
             9: from /mnt/myth/john/.gem/ruby/gems/asciidoctor-epub3-1.5.0.alpha.8/bin/asciidoctor-epub3:32:in `<top (required)>'
             8: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `invoke!'
             7: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `each'
             6: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:108:in `block in invoke!'
             5: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `convert_file'
             4: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `open'
             3: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `block in convert_file'
             2: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1502:in `convert'
             1: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1060:in `convert'
    /mnt/myth/john/.gem/ruby/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/converter.rb:35:in `convert': Encountered unexpected node in epub3 package converter: embedded (ArgumentError)

This is what I get when I leave "Embed Fonts" off when exporting from pages.

    asciidoctor-epub3 --trace -v -s JohnSchmittResume-Sept-2017.epub -o jsauto.pdf
    Traceback (most recent call last):
            21: from /mnt/myth/john/bin/asciidoctor-epub3:23:in `<main>'
            20: from /mnt/myth/john/bin/asciidoctor-epub3:23:in `load'
            19: from /mnt/myth/john/.gem/ruby/gems/asciidoctor-epub3-1.5.0.alpha.8/bin/asciidoctor-epub3:32:in `<top (required)>'
            18: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `invoke!'
            17: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:102:in `each'
            16: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:108:in `block in invoke!'
            15: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `convert_file'
            14: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `open'
            13: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575:in `block in convert_file'
            12: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1457:in `convert'
            11: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1341:in `load'
            10: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1341:in `new'
             9: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:463:in `initialize'
             8: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:463:in `new'
             7: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/reader.rb:569:in `initialize'
             6: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/reader.rb:65:in `initialize'
             5: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/reader.rb:582:in `prepare_lines'
             4: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/reader.rb:94:in `prepare_lines'
             3: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/helpers.rb:80:in `normalize_lines_array'
             2: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/helpers.rb:80:in `map'
             1: from /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/helpers.rb:80:in `block in normalize_lines_array'
    /usr/share/gems/gems/asciidoctor-1.5.6.1/lib/asciidoctor/helpers.rb:80:in `rstrip': asciidoctor: FAILED: /mnt/myth/john/resume/JohnSchmittResume-Sept-2017.epub: Failed to load AsciiDoc document - invalid byte sequence in UTF-8 (ArgumentError)

**Comment by mojavelinux** [comment]
I think you may be misunderstanding the purpose of this converter. This converter is for converting **from** AsciiDoc **to** EPUB3. It does not read an EPUB3 file.

**Comment by marmalodak** [comment]
Thanks for the explanation.
