### ISSUE TITLE
Uninitialized constant Asciidoctor::Epub3::GepubBuilderMixin::EOL (NameError)

### ISSUE THREAD

**Issue by anthonynelzin** [asciidoctor/asciidoctor-epub3#184]
Hi,

after a few weeks not using Asciidoctor EPUB3, I came back to a nasty surprise. Every conversion fails with the `uninitialized constant Asciidoctor::Epub3::GepubBuilderMixin::EOL`. With some sources, I get an ePub file anyways. With most sources, including the sample file from this repo, the conversion straight up stops. Here the trace: 

    /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:356:in `nav_level': uninitialized constant Asciidoctor::Epub3::GepubBuilderMixin::EOL (NameError)
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:348:in `block in nav_level'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:336:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:336:in `nav_level'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:326:in `nav_doc'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:307:in `add_nav_doc'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:282:in `block in add_content'
	from /Library/Ruby/Gems/2.3.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `instance_eval'
	from /Library/Ruby/Gems/2.3.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `resources'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:279:in `add_content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:591:in `block in package'
	from /Library/Ruby/Gems/2.3.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `instance_eval'
	from /Library/Ruby/Gems/2.3.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:507:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/packager.rb:507:in `package'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/lib/asciidoctor-epub3/converter.rb:41:in `write'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.5/lib/asciidoctor/document.rb:971:in `write'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.5/lib/asciidoctor.rb:1457:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.5/lib/asciidoctor.rb:1519:in `block in convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.5/lib/asciidoctor.rb:1519:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.5/lib/asciidoctor.rb:1519:in `convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.5/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.5/lib/asciidoctor/cli/invoker.rb:111:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.5/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-epub3-1.5.0.alpha.8/bin/asciidoctor-epub3:32:in `<top (required)>'
	from /usr/local/bin/asciidoctor-epub3:22:in `load'
	from /usr/local/bin/asciidoctor-epub3:22:in `<main>'

I'm using: 

- Asciidoctor EPUB3 1.5.0.alpha.8
- with Asciidoctor 2.0.5
- and Ruby 2.3.7p456
- on macOS Mojave 10.14.4

Any idea?

**Comment by mojavelinux** [comment]
Asciidoctor EPUB3 has not yet been tested, verified with Asciidoctor 2.0.

**Comment by mojavelinux** [comment]
This will be covered by #185.
