### ISSUE TITLE
wrong text in distribution section in releases tab

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-epub3#189]
Releases alpha.7, alpha.8 and alpha.9 mention `asciidoctor-pdf` instead of `asciidoctor-epub` in the distribuion name.

see: https://github.com/asciidoctor/asciidoctor-epub3/releases/tag/v1.5.0.alpha.9

**Comment by mojavelinux** [comment]
Thanks! All fixed.

(The link to the full diff was also wrong).
