### ISSUE TITLE
Hyperlinks to Bibliography does not work

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-epub3#19]
Consider the following 

**toplevel.adoc** (snippet of full toplevel document)

```
[chapter]
= Section title

include::aFile.adoc[]

[chapter]
= Bibliography

include::bib.adoc[]

```

**aFile.adoc** (the included section)

```
== A file
with text
== and this reference
* <<TestRef,Test reference text>>
```

**bib.adoc** (the included bibliography)

```
ifdef::backend-epub3[]
== Bibliography
endif::backend-epub3[]
[bibliography]
== Bib Section
- [[[TestRef]]] ysb33r. https://github.com/asciidoctor/asciidoctor-epub3
```

When rendered the `TestRef` will show up as a hyperlink, but when clicked will not move the document to the bibliography section

**Comment by mojavelinux** [comment]
> When rendered the TestRef will show up as a hyperlink, but when clicked will not move the document to the bibliography section

This link is supposed to allow you to jump between the bibliography entry and the first reference to it. However, if there are no references to it, the link is broken. A link should only be created if there's a corresponding reference to jump to.

**Comment by neontapir** [comment]
Is this resolved? I was able to reproduce this buggy behavior under the new build:

```
13:33 $ asciidoctor-epub3 -v
Asciidoctor EPUB3 1.5.0.alpha.7 using Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
13:33 $ asciidoctor-epub3 -D . toplevel.adoc
/usr/local/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
asciidoctor: WARNING: aFile.adoc: invalid reference to unknown local anchor (or valid bibref): TestRef
```

**Comment by mojavelinux** [comment]
@neontapir there are two cases here and only one of them was fixed. First, the link to the bibliography entry can't be validated (the case to which you are referring). That's a problem that stems from Asciidoctor core not cataloging these references. Second, the link from the bibliography entry back to the source wasn't working before. That's the side that got resolved. But even with the warning, the jumps should still work (as the warning message hints).

So we still have work to do. However, everything that needs to be done here is done. The change needs to happen in core. That's https://github.com/asciidoctor/asciidoctor/issues/560.

**Comment by mojavelinux** [comment]
I'll try to get that into 1.5.6 or 1.5.7.
