### ISSUE TITLE
Weird icons on epub format

### ISSUE THREAD

**Issue by amejiarosario** [asciidoctor/asciidoctor-epub3#193]
The icons on the HTML format look fine but the ePub got a weird bitcoin symbol
## ePub
![Screen Shot 2019-05-25 at 3 30 58 PM](https://user-images.githubusercontent.com/418605/58373807-1e81dc80-7f02-11e9-8ac6-0877a522c88c.png)

mobi
[image](https://user-images.githubusercontent.com/418605/58373789-cf3bac00-7f01-11e9-82bf-ac8212244bf6.png)

## HTML
![image](https://user-images.githubusercontent.com/418605/58373797-f5f9e280-7f01-11e9-9081-b2f2daac3fa2.png)

**Comment by mojavelinux** [comment]
The different icons are by design. However, the bitcoin icon was challenged so frequently that we decided to change it. If you upgrade to the latest release (1.5.0.alpha.9) you should see it's now a lightbulb. See #72.
