### ISSUE TITLE
Example doesn't produce a valid ebook

### ISSUE THREAD

**Issue by amejiarosario** [asciidoctor/asciidoctor-epub3#196]
I saw the travis command running `bundle exec asciidoctor-epub3 -D . data/samples/sample-book.adoc`. It's not validating that the epub is valid. If I run it with `-a ebook-validate ` I can see some errors
```
$ bundle exec asciidoctor-epub3 -D . -a ebook-validate data/samples/sample-book.adoc
asciidoctor: WARNING: asciidoctor-epub3-readme.adoc: invalid reference to anchor in unknown chapter: NOTICE
asciidoctor: WARNING: asciidoctor-epub3-readme.adoc: invalid reference to anchor in unknown chapter: LICENSE
asciidoctor: WARNING: asciidoctor-epub3-readme.adoc: invalid reference to anchor in unknown chapter: NOTICE
Epubcheck Version 3.0.1

Validating against EPUB version 3.0
ERROR: /Users/admejiar/Code/tmp/asciidoctor-epub3/sample-book.epub/OEBPS/asciidoctor-epub3-a-native-epub3-converter-for-asciidoc.xhtml(784,68): 'OEBPS/NOTICE.xhtml': referenced resource missing in the package.
ERROR: /Users/admejiar/Code/tmp/asciidoctor-epub3/sample-book.epub/OEBPS/asciidoctor-epub3-a-native-epub3-converter-for-asciidoc.xhtml(1129,115): 'OEBPS/LICENSE.xhtml': referenced resource missing in the package.
ERROR: /Users/admejiar/Code/tmp/asciidoctor-epub3/sample-book.epub/OEBPS/asciidoctor-epub3-a-native-epub3-converter-for-asciidoc.xhtml(1130,50): 'OEBPS/NOTICE.xhtml': referenced resource missing in the package.

Check finished with warnings or errors
```

**Comment by mojavelinux** [comment]
It's true, I probably never checked to see whether the sample was producing a valid ebook (since the focus was to demonstrate the converter, not necessarily make a valid ebook). But we probably should be producing a valid ebook.

**Comment by amejiarosario** [comment]
Since it's an example that people might follow (me included), I think it's good to have it working properly. And, I think it's valuable in case some new changes break functionality

**Comment by mojavelinux** [comment]
Fair enough. Do you want to fix it?

**Comment by amejiarosario** [comment]
Yes, I'll try and open a PR for it
-- 
- Adrian

**Comment by mojavelinux** [comment]
Thanks Adrian!

**Comment by slonopotamus** [comment]
Starting with c10e90703bf36940d106cf94e78c77307c4f7078, we started invoking examble book validation on CI. But the book is still invalid (this issue) and we still exit successfully even though book has errors (#215).

**Comment by slonopotamus** [comment]
Turns out, after #210 was fixed, sample book _is valid_. Closing.

**Comment by mojavelinux** [comment]
Nice!

**Comment by slonopotamus** [comment]
> Turns out, after #210 was fixed, sample book is valid.

No, I was wrong. I was testing on Windows and it is true that sample book doesn't produce errors. But. It doesn't include `README.adoc` and instead has untitled chapter!

This happened because `data/samples/asciidoctor-epub3-readme.adoc` is a symlink. Windows doesn't adequately support symlinks and even though Git for Windows has experimental symlink support, it is disabled by default.

So, instead of a symlink, `data/samples/asciidoctor-epub3-readme.adoc` is just a regular file with following contents:
```
../../README.adoc
```

Moral of the story:
1. Need more tests
2. Try to avoid storing symlinks in Git
