### ISSUE TITLE
Route messages through the logger

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-epub3#198]
Now that Asciidoctor core provides a logger, route messages from Asciidoctor EPUB3 through the Asciidoctor logger. Since Asciidoctor EPUB3 still supports versions of Asciidoctor that don't provide a logger, using a logger shim as was done in Asciidoctor PDF.

**Comment by slonopotamus** [comment]
Duplicates #176.

**Comment by mojavelinux** [comment]
OMG. I reported the same issue twice ;)
