### ISSUE TITLE
Cover image does not seem to preserve aspect ratio in kf8 output

### ISSUE THREAD

**Issue by michaelpj** [asciidoctor/asciidoctor-epub3#200]
I've specified the recommended size for the cover image, and in the epub output the image does stay at a fixed aspect ratio when I resize the viewer (I'm using `calibre`'s ebook viewer). However, in the kf8 output the cover resizes to fit the viewport, which I think isn't supposed to happen.

**Comment by slonopotamus** [comment]
I tried reproducing this using `bundle exec asciidoctor-epub3 -a ebook-format=kf8 data/samples/sample-book.adoc` in asciidoctor-epub3 repo, but do not observe the issue you're describing in Calibre 4.9.1:

![image](https://user-images.githubusercontent.com/92637/73962713-fc10e180-491f-11ea-8f0c-74b9bbea397d.png)
