### ISSUE TITLE
Date included even when `reproducible` is set

### ISSUE THREAD

**Issue by michaelpj** [asciidoctor/asciidoctor-epub3#203]
I think this is the offending line: https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/packager.rb#L565

**Comment by mojavelinux** [comment]
The reproducible behavior was never implemented in the EPUB3 converter. Feel free to submit a PR to implement it.

**Comment by slonopotamus** [comment]
Blocked by skoji/gepub#97. We _could_ hack around that, but I'd prefer to fix this on gepub side.

**Comment by michaelpj** [comment]
I think it also gets put into the output by this gem, it's not just the mtime of the resulting file.

**Comment by slonopotamus** [comment]
Sure, but this issue will only be resolved when our output is 100% reproducible. And this depends on gepub issue.

**Comment by slonopotamus** [comment]
Blocked by skoji/gepub#106

**Comment by mojavelinux** [comment]
How I solve this in other programs that require a date to be set (as zip does), is to set the date to the Unix epoch.

**Comment by slonopotamus** [comment]
I already did that, you can take a look at #296. There are just some unstable timestamps inside gepub.

**Comment by mojavelinux** [comment]
Then you're already on the right path. :+1:

**Comment by slonopotamus** [comment]
Okay, this now fully works if gepub >= 1.10 is used.
