### ISSUE TITLE
Can't make chapters which are "special" sections

### ISSUE THREAD

**Issue by michaelpj** [asciidoctor/asciidoctor-epub3#205]
e.g. a bibliography chapter.

See https://github.com/asciidoctor/asciidoctor/issues/3356 for discussion. Eventually we concluded that it's an issue with this gem if anything.

**Comment by mojavelinux** [comment]
See this comment for more info: https://github.com/asciidoctor/asciidoctor-epub3/issues/201#issuecomment-511933040

**Comment by slonopotamus** [comment]
@michaelpj Could you please provide an example document along with description of expected/actual behavior?

**Comment by michaelpj** [comment]
From what I recall, just make a book where one chapter is a bibliography, as in https://github.com/asciidoctor/asciidoctor/issues/3356.

**Comment by michaelpj** [comment]
My expected outcome is that it makes a chapter which is a bibliography. I don't remember where it goes wrong, I think it just doesn't get processed as a bibliography.

**Comment by slonopotamus** [comment]
Okay, so let a test case book for this issue be the following.

**book.adoc**
```adoc
= Bibliography book
:doctype: book

include::chapter.adoc[leveloffset=+1]

include::bibliography.adoc[leveloffset=+1]
```

**chapter.adoc**
```adoc
= Chapter

_The Pragmatic Programmer_ <<pp>> should be required reading for all developers.
To learn all about design patterns, refer to the book by the "`Gang of Four`" <<gof>>.
```

**bibliography.adoc**
```adoc
[bibliography]
= Bibliography

- [[[pp]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
From Journeyman to Master. Addison-Wesley. 1999.
- [[[gof,2]]] Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides. Design Patterns:
Elements of Reusable Object-Oriented Software. Addison-Wesley. 1994.
```
