### ISSUE TITLE
Problem with asciidoctor-bibtex

### ISSUE THREAD

**Issue by JWytrebowicz** [asciidoctor/asciidoctor-epub3#206]
The following command
  asciidoctor-epub3 -r asciidoctor-bibtex myText.adoc
generates myText.epub. 

The references are as expected. However, there is no bibliography in the document. Thus clicking on a reference goes nowhere, i.e. at the beginning of a given chapter. The same source files converted by asciidoctor to the HTML form give the expected result.

**Comment by mojavelinux** [comment]
I suggest you check with the asciidoctor-bibtex project about what is needed to support EPUB3 output. As I've never used the extension, I don't know what code I would need to change in asciidoctor-epub3 to support it (if any).

**Comment by ProgramFan** [comment]
I don't quite understand asciidoctor-epub3. asciidoctor-bibtex works as a tree processor which alters the AST produced by asciidoctor. It also uses a macro processor to add a placeholder that will be replaced by the bibliography in the tree processor. It seems that asciidoctor-epub3 interferes with the process.

**Comment by ProgramFan** [comment]
Any hint on this problem?

**Comment by mojavelinux** [comment]
Please provide an example project or else I cannot help you debug the problem.

**Comment by JWytrebowicz** [comment]
Here you go:
[excerpts.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/3438228/excerpts.zip)

The following command ends fine.
`asciidoctor -r asciidoctor-bibtex myText.adoc`

This one not so.
```
asciidoctor-epub3 -r asciidoctor-bibtex myText.adoc
asciidoctor: WARNING: 01part.adoc: invalid reference to unknown local anchor (or valid bibref): ITU-T2012
asciidoctor: WARNING: 01part.adoc: invalid reference to unknown local anchor (or valid bibref): W3C-WoT2019
asciidoctor: WARNING: 01part.adoc: invalid reference to unknown local anchor (or valid bibref): Lin2017
asciidoctor: WARNING: 01part.adoc: invalid reference to unknown local anchor (or valid bibref): IIoT-def
asciidoctor: WARNING: 01part.adoc: invalid reference to unknown local anchor (or valid bibref): IEEE42010-2011
asciidoctor: WARNING: 01part.adoc: invalid reference to unknown local anchor (or valid bibref): Aguzzi2014
```


By the way there is another problem. The cross references to defined anchors go nowhere. There are some of them int the attached files, i.e.: <<QR-def,QR>>, <<RFID-def,RFID>>, <<Urz-IoT-def,urządzenie IoT>>, <<IIoT-def,IIoT>>.

**Comment by ProgramFan** [comment]
The filename 01part.adoc looks strange. Does asciidoctor-epub3 create this file during the converting process? If so, I would need some help from the epub3 side on what I should do to keep the placeholder in that intermediate file.

**Comment by JWytrebowicz** [comment]
The .adoc and .bib files contain some excerpts from a book I am writing for my students. They are not created by asciidoctor-epub3. They can look strange for you as the content is in the Polish language. They contain some Asciidoc attributes, anchors and references apart the Polish text. The HTML file is created by the acsiidoctor command, and the epub file is created by the acsiidoctor-epub3 command.

**Comment by mojavelinux** [comment]
Those warnings could be harmless. Asciidoctor is just saying it can't validate bibrefs, so it notifies you to look into it.

Are you following the structure recommended by the README? In other words, do all other anchors work fine? https://github.com/asciidoctor/asciidoctor-epub3#structuring-your-manuscript

**Comment by JWytrebowicz** [comment]
OK. I gave  level-0 headings to every chapter placed in a separate file, and I gave them ID equal to the file names. I put the bibliography part into a separate file. It resulted in a proper generation of the table of contents. 
I took a look into the generated files: slowing.xhtml and 01part.xhtml. The references look fine, e.g. 
<a id="xref-QR-def" href="#QR-def" class="xref">QR</a>
<a id="xref--slownik--IIoT-def" href="slownik.xhtml#IIoT-def" class="xref">[slownik#IIoT-def]</a>
However there is not at all anchors in slownik.xhtml. Asciidoctor-epub3 do not generated them for a description list (https://asciidoctor.org/docs/user-manual/#description-list).
  
The generated bible.xhtml does not contain any text related to the source instruction "bibliography::[]". However references to the bibliography records are generated almost correctly, e.g.:
[<a id="xref-Aguzzi2014" href="#Aguzzi2014" class="xref">5</a>] 
– there is no stated the bible.xhtml file name.

Here is the archive of files I have played with:
[excerpts.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/3452337/excerpts.zip)

**Comment by ProgramFan** [comment]
I guess that asciidoctor-bibtex is not the only tree-processor in the epub-generating process. And the order by which they are invoked impacts the results. The placeholder generated by the block-macro-processor of asciidoctor-bibtex may get eliminated by asciidoctor-epub3. Is this the case? @mojavelinux
