### ISSUE TITLE
attributes ignored

### ISSUE THREAD

**Issue by jninja** [asciidoctor/asciidoctor-epub3#21]
If you set and `attribute` like this:

```
:appversion: 1.0.0
The current version of the application is {appversion}.
```

in rendered `.epub` output the attribute is ignored:

```
The current version of the application is {appversion}.
```

instead of the expected:

```
The current version of the application is 1.0.0.
```

**Comment by mojavelinux** [comment]
There's not enough information in this report for me to act on. Please reopen if you can provide more information.
