### ISSUE TITLE
large numbers of invalid `reference to unknown anchor` with links that appear to work, albeit poorly formatted

### ISSUE THREAD

**Issue by heckj** [asciidoctor/asciidoctor-epub3#210]
Using asciidoctor-epub3, version 1.5.0.alpha.9:

version string from code:
```
Asciidoctor EPUB3 1.5.0.alpha.9 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
(I'm using asciidoctor-docker image for rendering)

When I'm rendering the epub for a book project, I get a large number of warnings akin of the type `invalid reference to unknown anchor`. I've tracked them down to specific instances, and in each instance the link appears to be there, and rendered functionally correctly.

The source is public where I'm seeing this:

- https://github.com/heckj/swiftui-notes

This can be reproduced with the following sequence (assuming you have docker available locally):

```
git clone https://github.com/heckj/swiftui-notes
cd swiftui-notes
docker run --rm -v $(pwd):/documents/ --name asciidoc-to-epub3 asciidoctor/docker-asciidoctor asciidoctor-epub3 -v -t -D /documents/output docs/using-combine-book.adoc
```

A sample error:
`asciidoctor: WARNING: coreconcepts.adoc: invalid reference to unknown anchor in reference chapter: reference-map`

The layout of the book follows the recommended format, with the spine being in 'using-combine-book.adoc', although I do have the 'reference' chapter broken up into a number of smaller files pulled together with `include[]` structures.

The internal anchors are using the `[#chaptername-heading]` and referenced with `<<reference.adoc#chaptername-heading>>`. The links in this form render functionally correct, but with a visible text of `[reference#reference-assign]`. If I explicitly add the xreftext to the internal link, it's properly displayed (that is, in the form: `<<reference.adoc#chaptername-heading,LinkName>>` displays correctly as `LinkName`).

I'm not certain if this is a false alarm, related to the poorly constructed default link xreflabels, or something further. I've tried invoking with `--trace` but it doesn't give me any further clues, and I wasn't sure how to debug this further.

Is this a real issue, or an ephemeral one? And if real, are there any suggestions for how to narrow down and identify the issue I'm hitting that is generating the warnings?

**Comment by heckj** [comment]
(worth noting - PDF and HTML rendering doesn't exhibit this issue - it's only the ePub rendering that appears to be missing the xreflabel text from cross reference links)

**Comment by jnavila** [comment]
Have you read [this guide](https://asciidoctor.org/docs/asciidoctor-epub3/#composition-rules) and followed the rules?

**Comment by heckj** [comment]
@jnavila thanks for the ping - yes, definitely read the guide and have been following the rules. I did get sloppy with a few links and am resolving that now, but there's far more issues being reporting than I expected, and more-over - the cross-reference links *are* functional, they're just missing their xref-label text. I've been making a PR to explicitly add them throughout the book, but I'd love to know what I'm missing or messing up.

I did break one of my chapters up into a number of smaller files that I `included[]` into the "chapter", but even taking a stab at remerging that didn't appear to resolve the warning conditions.

I am wondering if I'm not correctly following expected level headings. Almost all of the xref links I've created are to subsections within chapters (technical documentation, so I'm trying to maintain a high amount of associative links). If certain level headers are expected for only chapters, I may be abusing the pattern in some fashion.

Is there an issue with cross-ref links to level 1, 2, 3, and 4 headings?

I am using `:leveloffset`: markers to make the layout of each subsection a bit more consistent when it comes to grouping - would this potentially be an issue?

Any further detail in how to get more details from the warning messages, or ways I can understand what's happening to debug my issue?

**Comment by jnavila** [comment]
OK. I just switched to asciidoctor 2.0.10 and my links that were previously working with 1.5.6.2 no longer work at all. I'm only using links with filenames.
@mojavelinux any hint?

**Comment by mojavelinux** [comment]
Yep, it looks like there's a bug in Asciidoctor EPUB3 when using Asciidoctor 2. It's looking in the wrong place for the reference.

**Comment by mojavelinux** [comment]
When I added support for Asciidoctor 2, I missed the case of a deep interdoc xref (meaning a reference somewhere inside the chapter).

**Comment by mojavelinux** [comment]
Thanks for reporting. PR sent.
