### ISSUE TITLE
Encoding issue in the name of the xhtml subpart when no id provided

### ISSUE THREAD

**Issue by mikrethor** [asciidoctor/asciidoctor-epub3#217]
I got a problem In all the xhtml file generated when an accentuated character is present in the title of the subdocument.

Let me give an example.

spine.adoc
```
= Asciidoctor EPUB3: Sample Book
Author Name
v1.0, 2014-04-15
:doctype: book
:producer: Asciidoctor
:keywords: Asciidoctor, samples, e-book, EPUB3, KF8, MOBI, Asciidoctor.js
:copyright: CC-BY-SA 3.0
// NOTE anthology adds support for an author per chapter; use book for a single author
:publication-type: anthology
:idprefix:
:idseparator: -

include::reference.adoc[]
```

reference.adoc
```
= Test é
```

The xhtml file generated for the reference.adoc get the name "test-Ã©.xhtml"

The accentuated character is rendered properly (test-é.xhtml) in the nav.xhtml, toc.ncx and package.opf

I would have liked the behavior to be consistent.
At least removing the accentuated character from the filename and all other reference in such case.

For now, I added an id in all the file with accentuated character.

I tried to look in the code to correct it any heads-up would be appreciated. I am not familiar with ruby.

I used the 1.5.0.alpha.9 version

Thx

Xavier

**Comment by mojavelinux** [comment]
I'm a bit rusty on the rules, but if my memory services me, it's EPUB3 and/or Kindle that doesn't allow accented characters in filenames. So I would recommend just avoid doing that. Set the ID explicitly to not include an accented character.

**Comment by slonopotamus** [comment]
EPUB spec allows unicode filenames: http://idpf.org/epub/301/spec/epub-ocf.html#sec-container-filenames

**Comment by mojavelinux** [comment]
> EPUB spec allows unicode filenames

This issue has come up before, but I misremembered the conclusion. I believe it was that zip files don't support the unicode filenames, or at least rubyzip doesn't. Either way, the error wasn't originating from the Asciidoctor EPUB3 code itself.

**Comment by slonopotamus** [comment]
> at least rubyzip doesn't

It does, though in umm... specific way. #243 is waiting for your review.

**Comment by mojavelinux** [comment]
> It does, though in umm... specific way

I should have said "didn't" at the time. I commented on the change. Looks like a necessary evil if we want to support this.

**Comment by slonopotamus** [comment]
However, see #162.
