### ISSUE TITLE
Seeking new maintainer

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-epub3#220]
Going forward, I will no longer be leading up the Asciidoctor EPUB3 converter project. In order for me to do what I need to do to evolve the AsciiDoc language and Asciidoctor ecosystem, I need to focus my attention on other parts of the stack. So I'm looking for a maintainer for this converter.

I'm committed to putting in the effort to ensure a smooth transition, and to play an ongoing role in supporting the maintainer. I just won't be working on new features or bug fixes in the converter itself. It also means you won't have to run changes through me. However, one requirement is that the new maintainer set up a test suite so that changes can be validated. The Asciidoctor PDF converter is a great reference for this task.

**Comment by slonopotamus** [comment]
Huh, why not?

My background: primarily, Java/C++ programmer with 15+ years experience. Able to read some 10th of other programming languages.

Maintaining [git-as-svn](https://github.com/bozaro/git-as-svn) project. Using asciidoctor for its documentation.

Really lazy and don't like to test stuff by hand, so introduce automated testing wherever possible. Including asciidoctor-epub3: #218, #222. Expanding testsuit by accompanying PRs with tests for affected functionality sounds like a good plan.

Have very minor Ruby experience, learning it currently. However, after certain number of languages learnt, they all are more-or-less the same (okay, except Haskell :) ). Would also like to add rubocop checking to asciidoctor-epub3 to assist following Ruby guidelines.

Do not have deep EPUB internals knowledge, however did web development for 5 years in the past, so not scared of HTML.

Do not own Kindle and most likely will never own one.

GitHub says I did 1k commits last year. I'd say this is a moderately active OSS contribution activity.

Hmm... Dunno what additional info I could provide. Maintaining asciidoctor-epub3 would be a side activity for me, though hopefully a fun to do.

**Comment by mojavelinux** [comment]
@slonopotamus Thanks for stepping forward!

> able to read some 10th of other programming languages...after certain number of languages learnt, they all are more-or-less the same...introduce automated testing wherever possible. Including asciidoctor-epub3

You really know how to win me over!

>  Would also like to add rubocop checking to asciidoctor-epub3 to assist following Ruby guidelines.

To be consistent with the Asciidoctor project, please use the configuration from [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/.rubocop.yml). That's where I'm grooming / refining the rules.

> Maintaining asciidoctor-epub3 would be a side activity for me

That's very much our culture in this project. And we are here to support each other.

I'll start by reviewing your PRs and if those look good (which I suspect they will), we can move to the next step.

**Comment by slonopotamus** [comment]
> please use the configuration from asciidoctor-pdf
Sure. I'll follow already existing practices wherever possible.

> And we are here to support each other.
Is there some kind of [gitter](http://gitter.im/)/maillist/IRC/whatever for asciidoctor development discussions?

> we can move to the next step
You're the boss here :) I just don't know what is the procedure.

**Comment by mojavelinux** [comment]
> Is there some kind of gitter/maillist/IRC/whatever for asciidoctor development discussions?

Yep. https://gitter.im/asciidoctor/asciidoctor

There's also a discussion list a https://discuss.asciidoctor.org, but that's more for user discussions.

**Comment by slonopotamus** [comment]
Fixed.

**Comment by mojavelinux** [comment]
Welcome @slonopotamus! We'll do the announcement / handover in the release notes. I'll tweet about it then so the community knows what's up.

As for practices, there are habits I have that I follow. If you have a different / better way of doing things, don't be afraid to suggest it. Sometimes I don't even remember why I do the things I do. Some thing are worth keeping. Other things aren't or need to be revisited. What's most important to me is consistency and communication. If you see a way to do something in an automated manner instead of manually, go for it.
