### ISSUE TITLE
Fix installation on Ruby 2.3 on Windows

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-epub3#229]
More modern Ruby versions were fixed by #213, but 2.3 is still broken.

This issue depends on tdtds/kindlegen#37.

**Comment by slonopotamus** [comment]
Quoting response in tdtds/kindlegen#37:

> NO. Support of Ruby 2.3 has ended. I don't want to support dangerous products.

**Comment by mojavelinux** [comment]
In that case, we have no choice. 2.4 has to be the minimum version the Asciidoctor EPUB3 supports. (We don't really need to support 2.3, we just hadn't made the leap in core yet, so we were trying to coordinate it...but we do what we have to do here).

**Comment by slonopotamus** [comment]
We can still go with 2.3 everywhere except Windows. Let it be so until 2.3 is dropped by whole Asciidoctor ecosystem.

**Comment by mojavelinux** [comment]
Good plan!
