### ISSUE TITLE
Drop the thread_safe gem dependency

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-epub3#234]
The thread_safe gem has been deprecated in favor of [concurrent-ruby](https://rubygems.org/gems/concurrent-ruby). Since the concurrent-ruby gem is already included, this is just a matter of removing thread_safe.

The thread_safe gem will still be requires to avoid a warning when using older versions of Asciidoctor core, but that can simply be documented.

**Comment by slonopotamus** [comment]
And why do we need `concurrent-ruby`? I do not see any multithreaded code anywhere in asciidoctor-epub3.

**Comment by mojavelinux** [comment]
You are correct that it is no longer required. Older version of Asciidoctor core would warn if the gem is absent, but that was fixed in Asciidoctor 2. Since most people will now be using Asciidoctor 2, I would just drop it and then see what feedback you get.

**Comment by mojavelinux** [comment]
To be clear, the gem is required when using custom templates. But that isn't typically done with Asciidoctor EPUB3.

**Comment by slonopotamus** [comment]
Yes, I am [getting a warning on 1.5.3](https://github.com/slonopotamus/asciidoctor-epub3/runs/399704522#step:6:8).
