### ISSUE TITLE
KF8/Mobi cannot be generated on modern MacOS without external Kindlegen

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-epub3#236]
kindlegen gem doesn't provide 64-bit binary for MacOS currently. And modern MacOS cannot execute 32-bit binaries. Upstream issue: tdtds/kindlegen#36.

**Comment by slonopotamus** [comment]
There's nothing we can do here unless there suddenly appears another way to produce KF8.

**Comment by mojavelinux** [comment]
cc: @mraible @wimdeblauwe

Related discussion: https://github.com/mraible/infoq-mini-book/pull/30#issuecomment-651563636

We likely need to get someone to host it somewhere (maybe bintray or S3) so that it can be downloaded. Or we could at least document the situation in the README to save people from going down rabbit holes.

**Comment by slonopotamus** [comment]
Agreed, we can document that Kindle Previewer for Mac bundles 64-bit kindlegen that can be used by asciidoctor-epub3via `KINDLEGEN` env variable.

**Comment by slonopotamus** [comment]
> We likely need to get someone to host it somewhere (maybe bintray or S3) so that it can be downloaded.

If kindlegen license allowed binary redistribution, things would be much easier and kindlegen gem would just bundle binary inside. But AFAIK this is not allowed.

**Comment by mojavelinux** [comment]
I think it's one of those things where someone should do it, and when Amazon complains, challenge that person to make it available so it isn't necessary. I get it is a violation, but of the protest variety.

**Comment by mojavelinux** [comment]
It looks like it's no longer possible to download KindleGen. https://www.amazon.com/gp/feature.html?docId=1000765211 (I really don't know what Amazon is doing).

One way we know to get it for now is to install the Kindle Previewer. If that works, we should document it. For automated scripts, we could also document the last known download URL. Here they are:

* Linux: http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz
* OSX: http://kindlegen.s3.amazonaws.com/KindleGen_Mac_i386_v2_9.zip
* Windows: http://kindlegen.s3.amazonaws.com/kindlegen_win32_v2_9.zip

We should be clear in the README that this is not our problem. We are doing our best to provide a way to generate MOBI, but it is Amazon that is making this unnecessarily difficult and complicated. What we offer is a convenience, but it's up to the user to get over Amazon's hurdles.

**Comment by slonopotamus** [comment]
Seems like Amazon wants people to use new `kindlepreviewer <file>.epub -convert` as a modern tool. 

But.

1. It is slow like hell (uses Java and PhantomJS)
2. It doesn't report errors to stdut/stderr, but instead produces CSV report file
3. It doesn't exist for Linux
4. Output file has `.kpf` extension. Calibre doesn't want to open that, even if I rename it to `.mobi`

**Comment by slonopotamus** [comment]
Okay, we're in trouble. All KindleGen download links now give Access Denied.

**Comment by slonopotamus** [comment]
Closing this in favor of #363 since the problem affects all platforms now.
