### ISSUE TITLE
asciidoctor-epub3 hangs on JRuby+Windows when converts data\samples\sample-book.adoc

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-epub3#253]
Way to reproduce:

0. asiidoctor-epub3 `master` branch
1. Windows (10 in my case)
2. JRuby (9.2.9.0 in my case)
3. `[jruby]\bin\bundle exec asciidoctor-epub3 data\samples\sample-book.adoc `

Expected: sample-book.epub is created

Actual: process hangs forever

**Comment by slonopotamus** [comment]
Minimized testcase:

book.adoc
```
= Da Book
:doctype: book

include::chapter.adoc[]
```

chapter.adoc:
```
= Teh Chapter

[source]
----
A
----
```

Now, try `bundle exec asciidoctor-epub3 book.adoc` and observe a hang.

**Comment by slonopotamus** [comment]
Given that pygments doesn't pass its own test suite on JRuby (tmm1/pygments.rb#190), by powers granted to me I disable usage of pygments.rb on JRuby.

**Comment by mojavelinux** [comment]
Pygments still works with Ruby on Linux. We have tests in Asciidoctor core and PDF that prove that. So let's not overstate this incompatibility.

**Comment by slonopotamus** [comment]
Note to myself: I have no information why pygments.rb was disabled on AsciidoctorJ before cb8c61a3af23fe07db4389c0debd1c0687b07499.

**Comment by mojavelinux** [comment]
There was a time very long ago that pygments.rb didn't work on JRuby. That changed as of pygments.rb 1.2. It should work.

**Comment by mojavelinux** [comment]
I think this exception needs to be more specific. It should be JRuby on Windows. I expect it to work on Windows with CRuby.
