### ISSUE TITLE
mobi file crashes Kindle for Mac

### ISSUE THREAD

**Issue by gregturn** [asciidoctor/asciidoctor-epub3#26]
I have created a document and build script at https://github.com/gregturn/asciidoctor-epub3-mac-for-kindle-bug.

This repo also contains a build trace and stack trace.

1. clone my repo
2. ./build
3. open Mobi file using Kindle for Mac
4. Ka-blam!

**Comment by gregturn** [comment]
BTW, the epub3 doc opened just fine in iBook on my Mac.

**Comment by mojavelinux** [comment]
I'll dive into this, probably by breaking out my OSX test machine to get a closer look. When I last worked on EPUB3, Kindle was frustrating me because their client for OSX still wasn't using the new KF8 engine. The KF8 engine uses WebKit. The earlier version used a pretty worthless rendering engine that only permitted a very limited set of HTML. I'm curious to see if KF8 is being used now. I can tell pretty easily when I see the interface which one it is.

**Comment by mojavelinux** [comment]
iBooks is the web we know, which is why it works :)

**Comment by gregturn** [comment]
Glad to help.

iBooks are nice, but since I have an iPad and my wife has an Android tablet, we have settled on the Kindle-formatted books. That way, we buy a book one time, and can read it anywhere.

It was super easy to experiment by staging books in my DropBox account. I'll see how they render on all my mobile devices. :)

**Comment by mojavelinux** [comment]
I want to clarify that the Kindle app for Android is excellent. Probably the best ebook viewer on Android. For some reason, it's just (or was) the pits for OSX.

> It was super easy to experiment by staging books in my DropBox account. I'll see how they render on all my mobile devices. :)

+1

**Comment by mojavelinux** [comment]
We came across this problem in the JHipster book. I think it's caused by #46. The workaround is to give each of your chapters an explicit id.

```
[[conventions]]
=  Gradle's Conventions
```

**Comment by gregturn** [comment]
:+1:

**Comment by mojavelinux** [comment]
I've also observed that if there are any warnings when creating the mobi file with Kindlegen, this leads to a crash downstream in Kindle for Mac. It's extremely fussy. I guess we're going to have to start a running lists of things that crash it so we know what to look out for.

**Comment by mojavelinux** [comment]
Though I really wish Amazon would just kill the terrible application that Kindle for Mac is and start over with the code base used for the app for Android.

**Comment by mojavelinux** [comment]
After digging a bit deeper, I think it's this line that is killing Kindle for Mac.

```
body p {
  -webkit-hyphens: auto;
}
```

There's a media query we can use to disable this for Kindle.

**Comment by gregturn** [comment]
I am happy to report that this repo now works properly at generating a mobi, so I'm deleting it.

**Comment by mojavelinux** [comment]
:+1:
