### ISSUE TITLE
Add support for alternative source code highlighter

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-epub3#262]
There are issues with pygments.rb:
1. It is disabled on JRuby+Windows due to bugs (#253)
2. It needs Python 2.7, which is EOL
3. It is not maintained

**Comment by mojavelinux** [comment]
I think this is premature. While I agree we need to start phasing out support for Pygments, I know there are a lot of builds that still rely on it. What I would do is aim to remove it in 2.0.0 (or 3.0.0 if 2.0.0 merely represents a shift to semver).

We will phase out pygments in Asciidoctor core at some point in the near-ish future, but not yet.

**Comment by mojavelinux** [comment]
We should start by strongly advocating for Rouge and getting everyone to be on board with it. Once we get the thumbs up that there are no major users of pygments, then we can phrase it out over a few releases.

The reason people still use Pygments is for the broader language support, and in some cases, custom language support. Rouge provides a way to define custom languages, but it might take time for the users to port the logic.

**Comment by mojavelinux** [comment]
Pygments still works with JRuby on Linux, so let's not overstate the incompatibility.

**Comment by slonopotamus** [comment]
Okay, I'll rephrase the issue.
