### ISSUE TITLE
Automated publishing to Maven repo

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-epub3#263]
Current process is:
1. asciidoctor-epub3 publishes a release
2. Time passes
3. Someone from AsciidoctorJ team becomes aware of a release
4. Time passes
6. He deploy release via asciidoctorj-epub3

Currently, `1.5.0.alpha.10` total delay is a full week and it isn't in Maven repo yet (asciidoctor/asciidoctorj-epub3#6).

I do not know any reasons why this procedure cannot be fully automated.

**Comment by mojavelinux** [comment]
The current process is based on Robert's availability. I agree that it shouldn't have to, but it's reasonable to understand why there's a delay given how the process works today. I think a release from this repo could trigger a script in that repo to handle the publishing. We'd only have to intervene if something failed.

**Comment by slonopotamus** [comment]
Okay, not now.
