### ISSUE TITLE
`cannot load such file -- kindlegen` on Linux

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-epub3#268]
Following on https://github.com/asciidoctor/asciidoctor-maven-examples/issues/77.
The issue still appears with alpha.11 building with maven and the gem, even on Linux.
For the gem build I am running `asciidoctor -b epub3 -r asciidoctor-epub3 -a ebook-format=kf8 spine.adoc`.

As another sad note, the workarround to call the maven build setting the envar `KINDLEGEN=$(which kindlegen)`, does not work with alpha.11, it did with alpha.10.

**Ruby environemnt**
Already installe Ruby 2.6.4 (ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux])
Gem installed
* `NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install asciidoctor-epub3 --pre`

**Maven environement**
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: ---/.sdkman/candidates/maven/current
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: ---/.sdkman/candidates/java/11.0.6.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.13-3-manjaro", arch: "amd64", family: "unix"

**Comment by slonopotamus** [comment]
Okay, there are two issues here:

1. We fail to load kindlegen gem on Maven
2. I f*cked up environment variable name in alpha-11

**Comment by slonopotamus** [comment]
Does it work if you manually install `kindlegen` gem?

**Comment by slonopotamus** [comment]
Too early to close this yet.

**Comment by abelsalgadoromeroWD** [comment]
> Does it work if you manually install `kindlegen` gem?

Do I need the gem? I have the `kindlegem`binary in my path.

**Comment by mojavelinux** [comment]
No, you shouldn't. The gem just installs the binary. In the upcoming release, the converter will detect it on your PATH if you don't set the KINDLEGEN env var (and the gem is not installed and we decide to make it optional). The alternative is to set the KINDLEGEN env var to the location of the binary.

**Comment by slonopotamus** [comment]
As I [said](https://github.com/asciidoctor/asciidoctor-epub3/issues/268#issuecomment-578546957), alpha-11 is unfortunately kinda broken WRT kindlegen path. I currently recommend either sticking to alpha-10 or installing `kindlegen` gem.

**Comment by abelsromero** [comment]
> I broke that in alpha-11 :( Already repaired back on `master`, but still.

haha 😆 shit happens to us all, don't be to hard on yourself. Moreover, it's alpha after all...

Just let me know when you think is ready to test, I can install the gem from master to test snapshots if necessary 👍 

PS: applogies for the account crossing. Alwasy forget to switch accouts when I am with the work machine.

**Comment by slonopotamus** [comment]
Okay, #276 was merged, I believe this bug can now be closed.

@abelsromero it would be great if you could test that `master` branch now works for you.

**Comment by abelsromero** [comment]
Will do! thx. If not today, tomorrow afternoon I can come with news

**Comment by slonopotamus** [comment]
@abelsromero okay, waiting for feedback from you. If everything's OK, I'll roll out alpha-12.

**Comment by abelsromero** [comment]
`master` branch working fine using Ruby in my Linux and Windows8.1 :+1:

**Comment by slonopotamus** [comment]
@abelsromero Thanks for your feedback!

> Only issue was that on Windows nokogiri does not support Ruby 2.7 and had to install 2.6.

Yeah, we're waiting for sparklemotion/nokogiri#1961.

**Comment by abelsromero** [comment]
> Yeah, we're waiting for [sparklemotion/nokogiri#1961](https://github.com/sparklemotion/nokogiri/issues/1961).

Does this mean this fix is blocked untill next nokogiri version is released?

**Comment by slonopotamus** [comment]
@abelsromero until that Nokogiri issue is fixed, we do not have Ruby-2.7 support on Windows. It doesn't block anything else.

To be more exact, the sequence is:

1. Nokogiri makes new release with Ruby-2.7 support
2. gepub upgrades to new Nokogiri (skoji/gepub#93) and makes a new release
3. asciidoctor-epub3 upgrades to new gepub

**Comment by flavorjones** [comment]
Nokogiri release candidate [v1.11.0.rc1](https://github.com/sparklemotion/nokogiri/releases/tag/v1.11.0.rc1) has been released with precompiled native libraries for Windows and Ruby 2.7. Please give it a whirl and let me know if you have any problems.
