### ISSUE TITLE
Move kindlegen out of optional deps

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-epub3#270]
Users suffer (#268):

```
$ gem install asciidoctor-epub3 --pre
$ asciidoctor -b epub3 -r asciidoctor-epub3 -a ebook-format=kf8 book.adoc
cannot load such file -- kindlegen
  Use --trace for backtrace
```

@mojavelinux Do you have arguments against this?

**Comment by slonopotamus** [comment]
Aaaargh, we can't because it is conditional =/ I'm not sure how to fix this then.

**Comment by mojavelinux** [comment]
I'd go ahead and make it a regular dependency.

**Comment by slonopotamus** [comment]
If 3.0.3 is added to gemspec, it can't be installed on Windows (#213). If 3.0.5 is added to gemspec, we lose Ruby 2.3 support (https://github.com/tdtds/kindlegen/commit/8c3b29c9cde2e4da73774d50fbdc1de14f5e249f).

**Comment by slonopotamus** [comment]
Okay, I think I figured out how to handle this: #272.

**Comment by mojavelinux** [comment]
The range is the correct thing to do. It allows the kindlegen gem to be installed first (or via Bundler), and installing this gem won't try to upgrade it.

You might not want to make the top of the range so specific. I think `< 3.1.0` would be sufficient.

**Comment by slonopotamus** [comment]
kindlegen doesn't follow semantic versioning (they raised Ruby version from 2.3 to 2.4 in kindlegen-3.0.4), so I'd prefer to play safe here.

**Comment by slonopotamus** [comment]
This will be undone, see #288.
