### ISSUE TITLE
-o [OPTION] ignored

### ISSUE THREAD

**Issue by jpliew** [asciidoctor/asciidoctor-epub3#278]
Hi team,

Just wondering if this is my system's problem? No matter what I typed after `-o` the generated `epub` will always follow `source` filename.

#### Using `-o adsf.epub`

```
ubuntu@user:~/bookname$ bundle exec asciidoctor-epub3 -D build/book -o adsf.epub  book.adoc
Wrote EPUB3 to /home/ubuntu/bookname/build/book/book.epub
ubuntu@user:~/bookname$ tree build/book/
build/book/
└── book.epub

0 directories, 1 file
```

#### Using `-o XXXX.epub`
```
ubuntu@user:~/bookname$ bundle exec asciidoctor-epub3 -D build/book -o XXXX.epub  book.adoc
Wrote EPUB3 to /home/ubuntu/bookname/build/book/book.epub
ubuntu@user:~/bookname$ tree build/book/
build/book/
└── book.epub

0 directories, 1 file
```

### Versions

```
ubuntu@user:~/bookname$ asciidoctor-epub3 -v
Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

ubuntu@user:~/bookname$ asciidoctor -v
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

 
```

Anyone has the same problem?

Cheers

**Comment by slonopotamus** [comment]
> asciidoctor-epub3 -v
> Asciidoctor **1.5.2**

This is your problem.  asciidoctor-epub3 finds very old version of Asciidoctor on your system. Note that minimal supported Asciidoctor version is 1.5.3. You should figure out where 1.5.2 comes from and possibly uninstall it.

This is how `asciidoctor-epub3` output is supposed to look like when using more modern Asciidoctor:
```
Asciidoctor EPUB3 1.5.0.alpha.11 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by slonopotamus** [comment]
Another possibility is `asciidoctor-epub3` itself is old. Support for Asciidoctor 2 was added in `1.5.0.alpha.9`.

You may use `gem list` to find out what exact gems you currently have installed and then `gem update`/`gem uninstall`.

**Comment by jpliew** [comment]
Thanks @slonopotamus , old version of `asciidoctor-epub3` is causing the problem. Cheers.
