### ISSUE TITLE
how this happened

### ISSUE THREAD

**Issue by myking520** [asciidoctor/asciidoctor-epub3#28]
C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1
.5.0.dev/bin/../lib/asciidoctor-epub3 (LoadError)
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.dev/bin/asciidoctor-epub3:3:in `<top (required)>'
        from C:/Ruby21-x64/bin/asciidoctor-epub3:23:in`load'
        from C:/Ruby21-x64/bin/asciidoctor-epub3:23:in `<main>'

**Comment by mojavelinux** [comment]
Somehow the gem didn't install correctly in your environment. I really don't know what other advice to give you at this point.

**Comment by ZacharyKlein** [comment]
I'm experiencing the same error.

**Comment by mojavelinux** [comment]
Have you used RVM? (rvm.io)

**Comment by ZacharyKlein** [comment]
I'm familiar with RVM but I haven't done anything with it so far - what should I do with it? Switch Ruby versions?

**Comment by ZacharyKlein** [comment]
```$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]```

**Comment by mojavelinux** [comment]
In my opinion, if you aren't using RVM, you don't yet have Ruby installed. You should never use the system Ruby for user operations. The system Ruby is for the system. RVM gives you a Ruby for you to use (for development, personal use, etc). On top of that, it sets up Ruby gems correctly so you don't get strange path errors. (Many systems install Ruby incorrectly and therefore can't install gems correctly...it's just I think I've observed).

**Comment by mojavelinux** [comment]
You setup RVM, then set the default Ruby to something other than system. Then, when you start a shell, life is good.

I recommend this guide:

https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rvm-on-ubuntu-16-04

(useful even if you don't use Ubuntu)

(I am planning to write a better guide for RVM. I'm just very tied up at the moment. I full recognize that the instructions from rvm.io leave a lot be desired).

**Comment by ZacharyKlein** [comment]
Thanks, I'm installing now. I was actually using the prerelease gem and getting the same error as in the original issue.

**Comment by mojavelinux** [comment]
:+1: I look forward to hearing how it goes. We'll get through this, that's for sure.

**Comment by ZacharyKlein** [comment]
@mojavelinux Same error, after using the nvm installed version of Ruby (2.2.6):

```
/Users/zak/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- asciidoctor (LoadError)
        from /Users/zak/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/zak/bin/asciidoctor-epub3/lib/asciidoctor-epub3.rb:1:in `<top (required)>'
        from /Users/zak/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/zak/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/zak/bin/asciidoctor-epub3/bin/asciidoctor-epub3:4:in `<main>'
```

**Comment by ZacharyKlein** [comment]
Installation worked fine, I get the error when trying to run `asciidoctor-epub3` outside of the installation directory in my asciidoc project

**Comment by mojavelinux** [comment]
Can you run `asciidoctor` outside of the installation directory? If not, can you run `gem install asciidoctor`?

**Comment by mojavelinux** [comment]
> Installation worked fine, I get the error when trying to run asciidoctor-epub3 outside of the installation directory in my asciidoc project

This is a clear case of a mixed up Ruby environment. It really doesn't have anything to do with this gem. You have binstubs that aren't in sync with the Ruby environment you are using. You'll face this same thing with any gem you try to use.

I intend to write a guide that explains how to get gems installed correctly so that you can use them without errors. Let's take it up there. See https://github.com/asciidoctor/asciidoctor.org/issues/399
