### ISSUE TITLE
Failed to parse source, undefined method `convert' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by igouss** [asciidoctor/asciidoctor-epub3#29]
H:\projects> gem install asciidoctor
Fetching: asciidoctor-1.5.2.gem (100%)
Successfully installed asciidoctor-1.5.2
Parsing documentation for asciidoctor-1.5.2
Installing ri documentation for asciidoctor-1.5.2
Done installing documentation for asciidoctor after 4 seconds
1 gem installed

H:\projects>asciidoctor -V
Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:- ex:IBM437)

H:\projects>git clone https://github.com/elastic/elasticsearch-definitive-guide.git
Cloning into 'elasticsearch-definitive-guide'...
remote: Counting objects: 10609, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 10609 (delta 36), reused 0 (delta 0), pack-reused 10535R
Receiving objects: 100% (10609/10609), 6.82 MiB | 3.14 MiB/s, done.
Resolving deltas: 100% (7800/7800), done.
Checking connectivity... done.

H:\projects>cd elasticsearch-definitive-guide

H:\projects\elasticsearch-definitive-guide>asciidoctor -trace -b epub -d book book.asciidoc
asciidoctor: FAILED: 'ace' could not be loaded
  Use --trace for backtrace

H:\projects\elasticsearch-definitive-guide>asciidoctor --trace -b epub -d book book.asciidoc
h:/p/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1362:in `rescue in load': asciidoctor: FAILED: H:/projects/elasticsearch-definitive-guide/book.asciidoc: Failed to parse source, undefined method`convert' for nil:NilClass (NoMethodError)
        from h:/p/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1281:in `load'
        from h:/p/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1458:in`convert'
        from h:/p/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
        from h:/p/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in`each'
        from h:/p/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
        from h:/p/Ruby22-x64/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/bin/asciidoctor:10:in`<top (required)>'
        from h:/p/Ruby22-x64/bin/asciidoctor:23:in `load'
        from h:/p/Ruby22-x64/bin/asciidoctor:23:in`<main>'

**Comment by dhinojosa** [comment]
Yeah I got this too. Now I can't create my slides. @mojavelinux ?

**Comment by mojavelinux** [comment]
What does this have to do with creating slides? Are you saying you get this error when you aren't using Asciidoctor EPUB3?

I'm not sure why it's attempting to load "ace". I don't even know what "ace" refers to. That's really strange.

**Comment by mojavelinux** [comment]
Oh, I see what's happening. You are using the flag `-trace` instead of `--trace` (two leading hyphens). The flag `-trace` is being interpreted as `-t` followed by `-r` followed by `ace` which attempts to load the library named "ace".

**Comment by mojavelinux** [comment]
That brings us back to the NilClass problem in convert. Looking into it.

**Comment by mojavelinux** [comment]
The problem here is that you aren't actually loading the epub3 backend (and epub isn't a valid built-in backend name).

You need to invoke Asciidoctor EPUB3 in one of two ways:

```
$ asciidoctor-epub3 -d book book.asciidoc
```

or

```
$ asciidoctor -r asciidoctor-epub3 -b epub3 -d book book.asciidoc
```

There are some warnings that are issued, but the book does generate. At the moment, Asciidoctor EPUB3 has very specific requirements for how the AsciiDoc must be structured. We do intend to loosen those requirements before we get to 1.5.0.

**Comment by mojavelinux** [comment]
The floating title isn't implemented in Asciidoctor EPUB3. I've opened an issue to address it. See #36.

**Comment by dhinojosa** [comment]
Great thank you. @mojavelinux. Yes, here was my error, just for infromational, perhaps not related to epub3.  But similar message.

± % asciidoctor -T ../asciidoctor-deck.js/templates/haml what_the_hell_are_math_nerds_talking_about_1.asc                                   !10216
asciidoctor: FAILED: /home/danno/documents/presentations/what_the_hell_are_math_nerds_talking_about/what_the_hell_are_math_nerds_talking_about_1.asc: Failed to parse source, Could not find a converter to handle transform: inline_quoted (RuntimeError)
  Use --trace for backtrace

**Comment by mojavelinux** [comment]
This message seems to happen if you point to a bogus backend. I'm not sure why (or if) it should fail earlier, but at least we know the linkage.

**Comment by mojavelinux** [comment]
This turned out to be a user error. I believe it has been addressed. Please comment or reopen if more investigation is warranted.
