### ISSUE TITLE
Inline images are not included

### ISSUE THREAD

**Issue by orloffm** [asciidoctor/asciidoctor-epub3#30]
Source:

```
image::red.png[]

A

image:blue.png[] B

Z
```

Resulting .epub does not have `blue.png` file, but it is referenced in the document.

**Comment by mojavelinux** [comment]
If I remember correctly, this is a known limitation because the AST does not return inline images.

See https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/packager.rb#L331

As long as that line gathers all the images, they will get packaged. However, we may need a change to core to expose this metadata.

**Comment by orloffm** [comment]
So the issue is that inline images are `Inline`, which are not `Block`, but `AbstractNode` instead? And one should implement `find_by` on `Inline`, right? Can you, please, find time for that?

The world of Ruby is alien to me, even if I manage to do that, I'll never handle doing tests properly.

**Comment by mojavelinux** [comment]
>  And one should implement find_by on Inline, right?

Unfortunately not. That gets to the heart of the problem. Inline syntax is not parsed during the parse phase. Inline syntax is discovered and converted in a streaming method. The only way to know about the inline images is to enable the `catalog_assets` option, then look for them in `document.references` after the conversion happens. Technically, this is possible, but it changes the strategy for how the images are added to the archive.

What I probably need to do is add the images to the archive after adding the content. That way, the documents will already be converted and therefore should have a reference to the images. I would switch from looking for images using `find_by` to getting the list of images from `document.references`.

**Comment by mojavelinux** [comment]
There is one workaround you can use. You can create a front-matter.html file and add all the inline images inside a comment block (or hidden element). The converter will add these images to the archive. (See https://github.com/asciidoctor/asciidoctor-epub3/blob/v1.5.0.alpha.6/lib/asciidoctor-epub3/packager.rb#L159-L167). The downside is that you will get a blank page in the EPUB3 file, though you could put something on this page just so it isn't blank.

**Comment by mojavelinux** [comment]
Solving this issue requires a rather deep understanding of how a) the EPUB3 packager works and b) how Asciidoctor manages images using `catalog_assets`. It's a tough one.

**Comment by ProgramFan** [comment]
This is really tough.

**Comment by mojavelinux** [comment]
Actually, it's not that tough now that we have performed processing of an inline macro in the mathematical extension. We either need to use a Treeprocessor or we can look at the image catalog after conversion. We may need to monkeypatch core in order to close some gaps, but it's definitely doable.

**Comment by Patola** [comment]
Agh. This bug is biting me HARD. Sorry because I know it is a difficult task, but any progress on that? I am using asciidoctor-mathematical for some formulas, and that's the last thing I need to render a proper epub.
