### ISSUE TITLE
Add series data

### ISSUE THREAD

**Issue by rvolz** [asciidoctor/asciidoctor-epub3#307]
There is currently no way to indicate series data, volume etc in AD. I have a working implementation here: https://github.com/rvolz/asciidoctor-epub3/commit/98a960168ccbee3209c197ce0eecb3c5961f3778

If there is interest to integrate that I could update it (the code is for older version)  and create a PR.

**Comment by slonopotamus** [comment]
Makes sense, though not sure anyone will use it. And it would be cool to find at least some software that understands this metadata to manually test that it works properly.

**Comment by rvolz** [comment]
Calibre can, of course:
<img width="281" alt="CleanShot 2020-02-20 at 10 32 54@2x" src="https://user-images.githubusercontent.com/1092531/74920458-7899ca80-53cc-11ea-8cbe-d627ddaa7676.png">

Other apps did too.

**Comment by slonopotamus** [comment]
Oh. I just looked at [comments in your commit](https://github.com/rvolz/asciidoctor-epub3/commit/98a960168ccbee3209c197ce0eecb3c5961f3778#diff-d73629a9901925280eac6371f3465954R566) and they suggested that Calibre doesn't handle it.
