### ISSUE TITLE
"Image not found or not readable" when data-uri attribute is set

### ISSUE THREAD

**Issue by agoncal** [asciidoctor/asciidoctor-epub3#324]
I was in version asciidoctorj-epub3::1.5.0-alpha.13 and this error message wasn't there. This message appears from 1.5.0-alpha.14 and now 1.5.0-alpha.15.

There are several issues about the image paths (#199 #124 #22). In my `spine.doc` I have something like this:

```
= {book-title}: {book-tech-long-name}
{author-name}
:data-uri:
:doctype: book
:imagesdir: ./images
:front-cover-image: image:jacket/cover.jpg[fit=fill]

// and many include:: with .adoc and images
```
From 1.5.0-alpha.14 I get this error message: 

```
[INFO] asciidoctor: ERROR: spine.adoc: image not found or not readable: /Users/agoncal/Dropbox (Quantixx)/Private/Technical/Projects/Fascicles/quarkus/quarkus-fascicle-practicing/src/main/asciidoc/data:image/png;base64,
```

Here I am just showing the first lines of the error message, but basically, the entire BASE64 appears underneath this line. The problem is that I get this message for every single image... but the images are acutally in the EPUB ?!?! 

So I don't understand this error message (and why it displays the BASE64) because the final result actually works.

**Comment by slonopotamus** [comment]
You want to remove `:data-uri:` attribute from document header. Turns out it isn't handled properly, I'll fix it.

**Comment by agoncal** [comment]
It works, thanks !

I removed the `:data-uri:` attribute and the BASE64 message is gone (and the images are displayed in the EPUB document).

@slonopotamus you say you gonna fix it, so what does it mean ? Shall we remove the `:data-uri:` for good ? Or put it back in v1.5.0.alpha.16 and the message won't be displayed ?

**Comment by slonopotamus** [comment]
`:data-uri:` forces images to be base64-encoded inside html pages instead of being packages as separate files inside epub archive. I am not actually sure why you would want to do that.

I heard that `:data-uri:` is used in asciidoctor-pdf to workaround something, though possibly they just set it explicitly nowadays, not sure. Anyway, asciidoctor-epub3 does not need `:data-uri:`.

I will fix an error that is produced in this case, so epub3 will just work with `:data-uri:` silently.

**Comment by mojavelinux** [comment]
> heard that :data-uri: is used in asciidoctor-pdf to workaround something

It has to do with the fact that Asciidoctor PDF has to read the image eagerly in order to embed it into the document. By setting data-uri, it forces Asciidoctor Diagram to produce an absolute image path, so Asciidoctor PDF can then read that file reliably.

**Comment by agoncal** [comment]
Ok, so for now I'm doing this so it works for all formats : 

```
ifndef::ebook-format-kf8[]
:data-uri:
endif::ebook-format-kf8[]
```
