### ISSUE TITLE
`toc::[]` macro causes a warning and is converted to "true"

### ISSUE THREAD

**Issue by programandala-net** [asciidoctor/asciidoctor-epub3#332]
Sometime ago i realized `toc::[]`causes "asciidoctor: WARNING: conversion missing in backend epub3 for toc" and text "true" is included in its position. I always use `ifdef::[]` to skip the `toc::[]` when the backend is EPUB, so there's no problem adding the TOC only to the proper target formats.

But the Asciidoctor warning that the TOC conversion is missing and the wrong output ("true") make 
me think maybe there's a bug somewhere. Ignoring the `toc::[]` macro would seem more logical after the warning. Or just throwing an error instead of a warning.

[test_01_toc_displays_true.adoc.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/4535655/test_01_toc_displays_true.adoc.zip)

**Comment by slonopotamus** [comment]
Thanks for providing example document. We already have a feature request for in-document TOC: #174. So, for current issue I'm going to fix that bogus "true" output (instead, nothing will be output in place of `toc::[]` though it'll still produce a warning), but TOC will remain unsupported and will later be implemented in #174.

**Comment by programandala-net** [comment]
Thank you. I had already searched for TOC issues and had read the feature request [#174](https://github.com/asciidoctor/asciidoctor-epub3/issues/174), but this little problem was different.
