### ISSUE TITLE
Support remote URLs for image/audio/video

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-epub3#333]
Subj. While it is not a common use case, @hepabolu wants exactly this and we can do it.

**Comment by slonopotamus** [comment]
@hepabolu I believe it _already_ works with current code, but produces an error because asciidoctor-epub3 tries to package find file in local filesystem in order to package it into epub archive. So if you're not scared by an error, you can just use current asciidoctor-epub3 release.

**Comment by hepabolu** [comment]
I can confirm that the audio control is correctly formatted. I do you you will fix the error, because it doesn't give a clue that the error is caused by trying to pack the file into the ePub.

**Comment by slonopotamus** [comment]
I fixed the code in aae419915189dcfe1d81a20773f6b7fd17acefd4 so it doesn't produce the error anymore and the fix will go into alpha-17 release. Until then, you can either ignore the error or use `master` branch.
