### ISSUE TITLE
Remote image/audio/video URLs need to be included in manifest

### ISSUE THREAD

**Issue by hepabolu** [asciidoctor/asciidoctor-epub3#334]
If audio or video files are too big to include in the ePub, it is preferable that they are hosted elsewhere. Resolving #333 support the remote URL but it often results in errors in Apple's Books reader on iPhone and iPad. In the best case the episode cannot be loaded in the audio control, in the worst case Books throws an error and crashes.

According to [EPUB Packages 3.2](https://www.w3.org/publishing/epub32/epub-packages.html#sec-item-elem) it seems that the remote URLs also need to be added to the manifest.

**Comment by slonopotamus** [comment]
Good catch. I also found that we do not add `remote-resources` for remote images. This will be fixed by skoji/gepub#116.

**Comment by hepabolu** [comment]
Thanks for the quick response. I just looked through your pull request and I wonder if that results in the outcome I think it should be. 

From the test you wrote I think you test if the xhtml file with a remote file gets the remote-resources property. Looking through the generated code in my project that already happens. 
What is missing in the manifest is the reference to the remote file itself. Not sure if that is added by your pull request.
