### ISSUE TITLE
Cell alignment and column width are ignored

### ISSUE THREAD

**Issue by programandala-net** [asciidoctor/asciidoctor-epub3#350]
The table cell alignment and column width are not preserved in the EPUB, while the same document produces the expected result with the Asciidoctor HTML backend or Asciidoctor PDF. Is it a bug or not supported?

I use the latest sources, from the repository.

Thanks.

**Comment by slonopotamus** [comment]
Could you provide an example document snippet please? Most likely this is simply incomplete tables support.

**Comment by programandala-net** [comment]
Of course. The source document is huge, but I had already extracted some of the tables in order to do some tests, before opening the issue. I attach an [example document tables.adoc.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/4893562/tables.adoc.zip)
with two small tables. Neither `col=` nor `>|` are obeyed. It seems default values are always used in EPUB.

**Comment by programandala-net** [comment]
Thank you for the fix. I'm checking all the tables and everything seems ok.
