### ISSUE TITLE
Hyperlink not resolved irc://chat.freenode.net/#kde

### ISSUE THREAD

**Issue by paulmcquad** [asciidoctor/asciidoctor-epub3#355]
I typed the following command into my file.asc:

.Table
|===
a|irc://chat.freenode.net/#kde[#kde] - Main channel for users of KDE software
|===

asciidoctor-epub3 -a ebook-format=kf8 file.asc

When i begin to build it creates this warning:
asciidoctor: WARNING: Warning(prcgen):W14001: Hyperlink not resolved:  /tmp/mobi-8y7GoF/EPUB/irc:/chat.freenode.net/#kde

**Comment by slonopotamus** [comment]
Hmm... Note that Calibre also doesn't handle `irc://` links. I start to think that the proper solution is to convert non-http links into a non-links.

**Comment by slonopotamus** [comment]
asciidoctor-epub3 no longer support producing MOBI/KF8, see https://github.com/asciidoctor/asciidoctor-epub3/pull/458.
