### ISSUE TITLE
Quotes no longer escaped in chapter title attributes

### ISSUE THREAD

**Issue by nelliemckesson** [asciidoctor/asciidoctor-epub3#358]
It looks like quotes are no longer being escaped in `title` attributes at the chapter level (at least).

E.g., in a document being transformed in book mode, this chapter header:

```
<h1 class="chapter-title"><small class="subtitle">3. Saying "Hello World"</small></h1>
```

is being converted to this:

```
<section class="chapter" title="3. Saying " hello="" world="" epub:type="chapter" id="hello_world">
```

I suspect it may be because the gsub was removed [here](https://github.com/asciidoctor/asciidoctor-epub3/commit/552171c3b6d035fa97231ef7a65a5eaefd6ed573#diff-459dde3aadb491ae5f3d27669367742aL385), leaving the transformation to rely on the `sanitize_xml` function, but cdata is [being passed](https://github.com/asciidoctor/asciidoctor-epub3/commit/552171c3b6d035fa97231ef7a65a5eaefd6ed573#diff-459dde3aadb491ae5f3d27669367742aR305) as the `content_spec`, rather than [attribute_cdata](https://github.com/asciidoctor/asciidoctor-epub3/blob/254e34c40301c87195dab36bd1215d1d5316e91b/lib/asciidoctor-epub3/converter.rb#L309)

**Comment by slonopotamus** [comment]
Whoops.
