### ISSUE TITLE
Rouge error: Improper use of Lexer#lex

### ISSUE THREAD

**Issue by fgm** [asciidoctor/asciidoctor-epub3#361]
Hello. When I try to compile a document, which compiles without error with the base asciidoctor and asciidoctor-pdf. asciidoctor-epub3 emits this error when using Rouge for highlighting :

```
$ asciidoctor-epub3 rapport.adoc
Improper use of Lexer#lex - this method does not receive options. This will become an error in a future version.
$
```

If I use  `:source-highlighter: pygments` instead, there is no equivalent error.

**Comment by slonopotamus** [comment]
So, looks like we don't need to do anything here.

**Comment by mojavelinux** [comment]
You don't. I need to get 2.0.11 released ;)

For the record, this warning is only shown when the source language is PHP and the `%mixed` option is not enabled on the block. No other language attempts to pass options to the lexer.
