### ISSUE TITLE
Dark mode links for internal links different per device

### ISSUE THREAD

**Issue by hepabolu** [asciidoctor/asciidoctor-epub3#366]
According to #338 the links are fixed in dark mode. After switching to version alpha.18 I can confirm that that is true for the external links. It is also true for the internal links (to a different chapter in the book) in Books for the Mac and for the iPad, but not for Books on the iPhone.

Mac/macOS Catalina
<img width="1075" alt="Screen Shot 2020-09-10 at 22 41 39" src="https://user-images.githubusercontent.com/7474858/92802983-44f9ae80-f3b7-11ea-8f1c-c90b84c659f5.png">

iPhone/iOS 13
![IMG_6684](https://user-images.githubusercontent.com/7474858/92803029-5347ca80-f3b7-11ea-9050-ea4f25f82ef2.png)

iPad/iPadOS 13
![IMG_0056](https://user-images.githubusercontent.com/7474858/92803267-8c803a80-f3b7-11ea-96b4-031b8d56f7a2.png)

It's the same ePub in all three devices.

Note the ToC links have the correct lightblue color in macOS Books, but the dark color in iPadOS and iOS.

Is there any way to fix this?

**Comment by slonopotamus** [comment]
Interesting. There will be some delay before I can investigate this, cause current top priority issue is #363 and I spend all time on it. If you have some time to play with CSS and fird out which rule is causing the problem, it would be awesome. I _thought_ I removed all link coloring, but this could be false.
