### ISSUE TITLE
Font resize doesn't work in Apple Books

### ISSUE THREAD

**Issue by hepabolu** [asciidoctor/asciidoctor-epub3#368]
With the default theme, the font will not resize in Apple Books on iPad or iPhone (iPadOS/iOS 13). It will resize in Apple Books for Mac.

When pressing the increase/decrease font button, the page reflows, to show less or more text resp. but the actual font stays the same.

**Comment by slonopotamus** [comment]
@mojavelinux Could you possibly remember why you added `-webkit-text-size-adjust: 100%` in the first place? Though I'm kinda surprised that it results in described behavior, docs do not say it would lock font size (unlike `-webkit-text-size-adjust: none`).

**Comment by mojavelinux** [comment]
It was to fix the issue described on this page. https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust I never observed the behavior myself and was basing the decision to include it on that recommendation. If it only causes problems, then I suppose it can be removed.
