### ISSUE TITLE
Manifest file still doesn't contain references to external video

### ISSUE THREAD

**Issue by hepabolu** [asciidoctor/asciidoctor-epub3#369]
Using alpha.dev.18 the links to external video files, still don't end up in the manifest.

```
pass:m,a[<audio controls='controls' 
src="{url-mp3}/TTT30SSHingMoreSecurely/TTT_30_SSHing_More_Securely.mp3">
Your browser does not support HTML 5 audio</audio>]
```

resolves correctly to an audio player that plays the audio and is correctly marked up with 'remote-resources' in package.opf

```
<item id="item_ttt30" href="ttt30.xhtml" 
media-type="application/xhtml+xml" properties="remote-resources scripted"/>
```

However, I would expect that the video reference would also be part of the package.opf, like this:

```
<item id="mp3ttt30" 
href="https://media.blubrry.com/tamingtheterminal/archive.org/download/TTT30SSHingMoreSecurely/TTT_30_SSHing_More_Securely.mp3" 
media-type="audio/mpeg"/>
```

but it isn't. This causes the epubcheck to throw errors.

Workaround: 
* manually build the list of missing items
* run a script like the one below

```bash
#!/bin/bash
#
# Due to a bug in the asciidoctor-epub3 generator, the
# references to the podcasts are not added to the package.opf file
#
# let's fix that here
# 
# ttt.epub = epub file with missing references
# output = location where ttt.epub ends up after generation
# publish/external_resources.xml contains the missing items

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# remove prior unpacked versions
rm -rf "${DIR}/../output/ttt"
mkdir -p "${DIR}/../output/ttt"
cd "${DIR}/../output/ttt"

unzip ../ttt.epub
cp ../ttt.epub ttt-fixed.epub

sed -i.BAK '/<\/manifest>/{
    r '${DIR}/../publish/external_resources.xml'
    a\
    <\/manifest>
    d
}' EPUB/package.opf

rm -rf */package.opf.BAK
zip -r ttt-fixed.epub EPUB/package.opf
mv ttt-fixed.epub ../ttt.epub
cd - > /dev/null
rm -rf "${DIR}/../output/ttt"
```

**Comment by slonopotamus** [comment]
Hmm... I'm kinda confused why you're adding audio that way. You're effectively bypassing all Asciidoctor-EPUB3 handling of audio/video. Why you're not doing it with

```asciidoc
audio::{url-mp3}/TTT30SSHingMoreSecurely/TTT_30_SSHing_More_Securely.mp3[]
```
?

**Comment by hepabolu** [comment]
I certainly tried it that way, but there was a reason I needed to revert to the above notation. I will try to find out the reason why.

**Comment by hepabolu** [comment]
I cannot reproduce the behavior I found earlier. I've changed the notation to your suggestion and I can confirm that this fixes my problem.
