### ISSUE TITLE
Ids in package.opf are not valid when images are encoded in base64

### ISSUE THREAD

**Issue by agoncal** [asciidoctor/asciidoctor-epub3#371]
Take the following document:

```
= Test

This is an image <<commons-figure-asciidoc>>.

[[commons-figure-asciidoc]]
.Author
image::commons-figure-asciidoc.png[]
```

Once you generated the EPUB version, the image in `package.opf` as a valid id (here, the nane of the caption):

```
<item href="./images/commons-figure-asciidoc.png" id="item_commons-figure-asciidoc" media-type="image/png"/>
```

But when you set `:data-uri:` the id is invalid. Take the following doc:

``` 
= Test
:data-uri:

This is an image <<commons-figure-asciidoc>>.

[[commons-figure-asciidoc]]
.Author
image::commons-figure-asciidoc.png[]
```

Now, if you check the `package.opf` you can see the base64 format of the image. The id is set to the last characters of the base64 (here `AyouyzE6v5n4AAAAAElFTkSuQmCC==`). 

```
<item href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAACMAAAAanCAIAA.../AyouyzE6v5n4AAAAAElFTkSuQmCC==" id="item_AyouyzE6v5n4AAAAAElFTkSuQmCC==" media-type=""/>
```

When you run EPUBCheck, you get the following error. The `id` attribute is not valid XML:

```
<message id="RSC-005" severity="error">RSC-005, ERROR, [Error while parsing file: value of attribute "id" is invalid; must be an XML name without colons], EPUB/package.opf (50-1127779)</message>
```

The generated id should be XML valid so we don't get this kind of messages

**Comment by mojavelinux** [comment]
The recommendation I would make here is that the converter should prevent the data-uri attribute from being set. It's not relevant for this converter since it already bundles the images (plus it would make the HTML pages too big for the eReader to load quickly).

**Comment by slonopotamus** [comment]
This worked in the past but was broken by https://github.com/asciidoctor/asciidoctor-epub3/commit/6f876a571563cad1901da3c42312b76ee97e3846#diff-93ca17fc89a99225907ad6e973edca6adbed70d77f7cf6eddd1d08ab59838d10L933.

**Comment by agoncal** [comment]
This rang a bell. This is the issue [I had a few years ago](https://github.com/asciidoctor/asciidoctor-epub3/issues/324#issuecomment-602278666) and the comment of @mojavelinux:

> heard that :data-uri: is used in asciidoctor-pdf to workaround something

> It has to do with the fact that Asciidoctor PDF has to read the image eagerly in order to embed it into the document. By setting data-uri, it forces Asciidoctor Diagram to produce an absolute image path, so Asciidoctor PDF can then read that file reliably.

**Comment by mojavelinux** [comment]
I'm pretty sure we've since worked out a better integration with Asciidoctor Diagram. I need to check in Asciidoctor PDF whether that workaround is even necessary anymore. It certainly shouldn't be necessary as it's very obtuse.

**Comment by agoncal** [comment]
@mojavelinux I've just checked, and the PDF and the EPUB are alright without `:data-uri:`. But now, I have an issu with the HTML version. Without the `: data-uri:` the HTML generated code looks like this:

```
<img src="./images/commons-figure-asciidoc.png" alt="commons figure asciidoc">
```

The issue is that the HTML page is generated under the `target/generated-asciidoc` and the image under `target/generated-docs/images`. So `./images` does not find the image. 

```
target/
├── generated-asciidoc
│   └── commons-test-asciidoc-1.0.html
└── generated-docs
    └── images
        └── commons-figure-asciidoc.png
```

I realize that I've been using `:data-uri:`for years, always embedded my images as base64 and never had to deal with path issues.

**Comment by abelsromero** [comment]
>  But now, I have an issu with the HTML version. Without the `: data-uri:` the HTML generated code looks like this:

This seems related to the maven-plugin.
This works fine for me, all resides inside _generated-asciidoc_.

```xml
<configuration>
    <backend>html5</backend>
    <outputDirectory>${build.outputDirectory}/generated-asciidoc</outputDirectory>
    <attributes>
        <imagesdir>./images</imagesdir>
    </attributes>
</configuration>
```

But if you have troubles, you can force where asciidoctor-diagram generates the images: https://github.com/asciidoctor/asciidoctor-diagram#image-output-location

PS: If you still have problems, let's move this to the maven repo.

**Comment by agoncal** [comment]
@abelsromero Yes, indeed. I was using a wrong variable in my Maven plugin :o(

Thanks for your help
