### ISSUE TITLE
Inline pass macro `m` not working

### ISSUE THREAD

**Issue by agoncal** [asciidoctor/asciidoctor-epub3#375]
The following document displays an icon and some formatted text:

```
= Test
:icons: font

icon:hand-o-right[] *Call to Action*
```

Because I use this text very often, I made a variable out of it (see [1]) using the `m` and `q` passthrough macros:

```
= Test
:icons: font
:call-to-action: pass:m,q[icon:hand-o-right[] *Call to Action*]

{call-to-action}
```

This breaks in EPUB (works for PDF and HTML) with the following error:

```
Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc (output-epub) on project commons-test-asciidoc: Execution output-epub of goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc
failed: org.jruby.exceptions.NoMethodError: (NoMethodError) asciidoctor: 
FAILED: spine.adoc: 
Failed to load AsciiDoc document - undefined method `<<' for nil:NilClass
```

If you decompose the inline pass through, the `q` macro works (quote substitution[2]):

```
= Test
:icons: font
:call-to-action: pass:q[*Call to Action*]

{call-to-action}
```

But not the `m` macro

```
= Test
:toc:
:icons: font
:call-to-action: pass:m[icon:hand-o-right[]]

{call-to-action}
```

[1] https://github.com/asciidoctor/asciidoctor/issues/3773
[2] https://asciidoctor.org/docs/user-manual/#inline-pass-macro-and-explicit-substitutions

**Comment by slonopotamus** [comment]
@mojavelinux Ouch. Asciidoctor-EPUB3 expected that the first thing that will go through `convert` is document and do lots of converter setup there. But with given document, this happens first:

     NoMethodError:
       asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `<<' for nil:NilClass
     # ./lib/asciidoctor-epub3/converter.rb:1172:in `convert_inline_image'
     # ./lib/asciidoctor-epub3/converter.rb:106:in `convert'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/inline.rb:32:in `convert'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb:430:in `block in sub_macros'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb:414:in `gsub'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb:414:in `sub_macros'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb:102:in `block in apply_subs'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb:91:in `each'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb:91:in `apply_subs'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1113:in `apply_attribute_value_subs'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:854:in `set_attribute'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:2135:in `store_attribute'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:2092:in `process_attribute_entry'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:2071:in `process_attribute_entries'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:1783:in `parse_header_metadata'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:168:in `parse_document_header'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:92:in `parse'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:549:in `parse'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/load.rb:83:in `load'
     # ~/.gem/ruby/2.5.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:78:in `convert'

Is it by design?

**Comment by mojavelinux** [comment]
Yes, it's possible that the converter can be called for an inline node before convert has been called on the document node. This is primarily due to the need to generate a section ID.

We have the same challenge in the PDF converter. The way we handle it there is to push any initialization code that is needed to convert an inline node (such as loading the theme) into a lazy loading method. That way, the minimum amount of initialization occurs on demand.

**Comment by mojavelinux** [comment]
...and in this case, it happens because substitutions are being forced on an attribute entry value.

However, that's not even necessary in this case. The macro substitution happens after attribute substitution, so the following would work as is:

```
:call-to-action: pass:q[icon:hand-o-right[] *Call to Action*]
```

Only the quote substitution needs to be forced eagerly.

**Comment by agoncal** [comment]
Oh, yes, I don't need the `m` macro to display the icon. So it works with just the `quote`. Thanks

**Comment by agoncal** [comment]
Thanks @slonopotamus for killing so many issues in the last days, thank you very much.

Do you know when v1.5.0.alpha.19 will be released ?

**Comment by slonopotamus** [comment]
@agoncal [BAM!](https://github.com/asciidoctor/asciidoctor-epub3/releases/tag/v1.5.0.alpha.19) Since you're using asciidoctor-epub3 via maven plugin, you'll need to [wait a bit](https://github.com/asciidoctor/asciidoctorj-epub3/pull/14).

**Comment by agoncal** [comment]
You are amazing @slonopotamus. Thanks. Just in time for the release on my book next week. I'll have a fantastic EPUB version thanks to you ;o)
