### ISSUE TITLE
Error while parsing file: value of attribute "width" is invalid; must be an integer

### ISSUE THREAD

**Issue by dismine** [asciidoctor/asciidoctor-epub3#382]
Hi.

I try to create epub version of my book. And validation shows a lot of errors like this. Is it okay or I must do something with it?

My images defined like this:
`image::images/image.png[pdfwidth=75%, scaledwidth=60%, align="center"]`
which in epub will be converted to
`<img src="images/11-section-4.png" alt="11 section 4" width="60%" />`

**Comment by mojavelinux** [comment]
@slonopotamus using the style attribute for the width has the potential to make the AsciiDoc non-portable. The converter should only allow an integer or a percentage (which is what the width attribute in HTML allows, but apparently the validator is being more strict than what HTML allows).

**Comment by slonopotamus** [comment]
Hmm... I maybe was too quick with it. Let me recheck all this situation.

**Comment by slonopotamus** [comment]
@mojavelinux According to the [spec](https://www.w3.org/TR/2011/WD-html5-20110113/the-map-element.html#attr-dim-width), dimension attributes are not allowed to be percentage even in HTML5.

**Comment by slonopotamus** [comment]
I think I want to change logic to "if attribute value parses as an integer, use `width="..."`. Otherwise, use `style="width: ..."`

**Comment by mojavelinux** [comment]
> According to the spec, dimension attributes are not allowed to be percentage even in HTML5

You're right, though this is one of those things that is rarely enforced and actually has its own unique behavior that cannot be replicated (it doesn't always behave the same as the style width, such as in tables).

Regardless, the width attribute is meant to be an integer only. The scaledwidth can be any value that the style attribute accepts. So your plan is sound, as long as it doesn't allow the width attribute to be something like 1em.
