### ISSUE TITLE
asciidoctor: ERROR: Error(core):E1008: Failed conversion to unicode. The resulting string may contain wrong characters.

### ISSUE THREAD

**Issue by dismine** [asciidoctor/asciidoctor-epub3#383]
When I generate MOBI version with 
`KINDLEGEN=/usr/local/bin/kindlegen asciidoctor-epub3 -a ebook-compress=standard -a ebook-format=kf8 index.adoc`
I get 
`asciidoctor: ERROR: Error(core):E1008: Failed conversion to unicode. The resulting string may contain wrong characters.`

Though I get a mobi document that seems to work fine.

**Comment by slonopotamus** [comment]
This is a message from Kindlegen. In the light of #363, I doubt any further work on Kindlegen is worth it.

**Comment by slonopotamus** [comment]
Could you please retest with changes from https://github.com/asciidoctor/asciidoctor-epub3/pull/434? If the error still occurs, I'm afraid I need some repro document that triggers the issue.
