### ISSUE TITLE
cover is not attached for the mobi version; doctype is not `book`

### ISSUE THREAD

**Issue by radekosmulski** [asciidoctor/asciidoctor-epub3#403]
I generate the book with the following in the `adoc` file

```
= Book Title
My Name <my_name@gmail.com>
:doctype: book
:imagesdir: images
:toc:
:notitle:
:front-cover-image: image:cover_JPG.jpg[Book Title,1600,2560]
```

I generate the book using either the first or the second command below (no difference):

```
asciidoctor-epub3 -a front-cover-image=images/cover_JPG.jpg -a ebook-format=kf8 book.adoc
```
or
```
asciidoctor-epub3 -a ebook-format=kf8 book.adoc
```

The generation goes through without error, but when I send the file to kindle (using gmail, sending it to my own kindle address), the cover is not showing. The book has type `doc` and not `book`.

**Comment by radekosmulski** [comment]
If I don't send the book via email but copy it over via USB it all works! Sorry about this - closing.

**Comment by slonopotamus** [comment]
No need to sorry, we found out something new today :)
