### ISSUE TITLE
Front cover image is not set for epub

### ISSUE THREAD

**Issue by rshiva** [asciidoctor/asciidoctor-epub3#421]
Hi, 
I am trying to set an image as the front cover instead of the title. Below is the code

= Title of the book
Author Name
v1.0
:doctype: book
:chapter-label:
:chapter-number:
:epub-chapter-level: 2
:description: This guide describes the Asciidoctor attributes, values, and layout options available for producing a customized and polished document.
:imagesdir: app/assets/images
:notitle:
:front-cover-image: image:generated.jpg[Book Title,1050,1600]
:toc:

I generate epub using the below command

asciidoctor-epub3 -D output -a ebook-format=epub3  -a data-uri -a allow-uri-read book.adoc --verbose

After generating I'm sending the epub through email. I can see only the "Title of the book" on the cover,it looks something like this

![IMG_5620](https://user-images.githubusercontent.com/594344/186040288-e9bcc5d5-4b64-42a5-bede-45bb60fe5542.jpg)

Am I Doing anything wrong? This issues is similar to #403 .

**Comment by rshiva** [comment]
@slonopotamus any help is appreciated. :)

**Comment by mojavelinux** [comment]
The issue tracker is not a support channel. If you need help regarding the usage of an Asciidoctor project, please direct your question to the project chat at https://chat.asciidoctor.org. See https://docs.asciidoctor.org/about/support/ to learn about the support policy of the Asciidoctor project.

**Comment by rshiva** [comment]
@mojavelinux  Sorry!!. Thanks for directing me to the chat and support link. I have only raised an issue because I found a similar #403. I thought it might be a bug.

**Comment by mojavelinux** [comment]
No worries. I'm not saying that it isn't a bug...but if you are looking for help on how to move forward one way or another, then the chat is the right place. Issues will be looked at when the maintainer has time, and that might not be on a time schedule that aligns with your needs. That's why we have the chat. You can find help among a group of 500+ who hang out there.

**Comment by slonopotamus** [comment]
@rshiva 

1. Are there any warnings/errors when you generate EPUB?
2. Does cover image show properly on your PC? For example, in [Calibre](https://calibre-ebook.com/)?
3. You said something about sending by email. Is that [Send to Kindle](https://www.amazon.com/sendtokindle) feature? It is known to [damage books a lot](https://docs.asciidoctor.org/epub3-converter/latest/#send-to-kindle) and better be avoided.

**Comment by slonopotamus** [comment]
No response for a year, closing.
