### ISSUE TITLE
apostrophes render incorrectly when EPUB output is sent to Kindle

### ISSUE THREAD

**Issue by radekosmulski** [asciidoctor/asciidoctor-epub3#437]
I encountered the following issue with my book.

When I open the EPUB version using calibre on windows, the apostrophes render okay:
![image](https://user-images.githubusercontent.com/2444926/211530249-fca9ed71-9213-4113-97c7-bef52f7ed41c.png)

When I send the EPUB file to kindle, the apostrophes are garbled up:
![image](https://user-images.githubusercontent.com/2444926/211530441-cc0ebe30-05d4-4510-bdd7-5192ae3182d0.png)

I found [a reddit thread discussing this](https://www.reddit.com/r/kindle/comments/ufmc96/dont_start_sending_epubs_to_amazon_yet_awz3_vs/). According to the thread:

> This problem is results from the original EPUB file lacking the "encoding" markup in its HTML files to indicate that UTF-8 character encoding is being used. In that case Amazon's EPUB converter assumes the encoding to be Latin-1 for historical reasons, resulting in non-ASCII characters such as curly quotes being rendered incorrectly. Opening the EPUB in Amazon's Kindle Previewer will show the same result. This is that way it has always been and is unlikely to change.

Could I please ask how I could fix the issue for my readers? Is there any way to specify the encoding as `UTF-8` in the EPUB file or any other way to fix this?

Thank you so much for your help!

**Comment by slonopotamus** [comment]
This was already fixed in #424, it just wasn't released yet.
