### ISSUE TITLE
Images not rendering in Apple iBook

### ISSUE THREAD

**Issue by bjoernsteffens** [asciidoctor/asciidoctor-epub3#439]
I am on the Mac platform and when converting the adoc file to epub the images are not included.

Here is the adoc file to reproduce the problem. The collateral to reproduct the problem is attached as zip.

= Document Title
Bjoern Steffens <bjoern.steffens1@gmail.com>
:doctype: book
:revnumber: 1.1
:revdate: 20.02.2023
:revremark: Updated load charts.
:icons: font
:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 2
:imagesdir: ./images

== Appendix A - Compute Resource Utilization

=== vSphere hardware
.vSphere hardware
image::system_esx_hw.png[]

=== OpenShift idling
.OpenShift only and idling
image::system_load_ocp_only.png[]

=== TheThing installation
.CPTheThing4D installation
image::system_load_cp4d_installation.png[]

=== OpenShift and TheThing idling

.OpenShift and TheThing idling
image::system_load_cp4d_idling.png[]

[epub3_image_issue.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/10783139/epub3_image_issue.zip)

**Comment by slonopotamus** [comment]
I've opened `epub3_image_issue.epub` from your zip (thanks for detailed repro, btw) and I _do_ see images in Calibre. What EPUB reader you're using?

**Comment by bjoernsteffens** [comment]
I am using the Books app on the MacBook. I just installed Calibra 6.13 and I can see them there too. This is however not a practible solution to ask people to get Calibre installed. This does however trigger the Q if the Books app on the Apple platform has an issue or not.

**Comment by bjoernsteffens** [comment]
On my iPad I tried the file with the Yomu Ebook Reader and the images are visible. Can we narrow things down to the Apple iBooks eco-system?

**Comment by slonopotamus** [comment]
Could you please try `:imagesdir: images` instead of `:imagesdir: ./images`?

**Comment by bjoernsteffens** [comment]
Change applied and still the same observeration in iBook.

However, if I tap or click on the "question mark icon" on the MacBook or the iPad the images are display. There is no setting in the iBook app to permanently show images by default. 

To be honest this is an Apple iBook issue and I would not like to take up more of your time because in any other ePub reader things are working fine.

**Comment by bjoernsteffens** [comment]
:-/

**Comment by slonopotamus** [comment]
I've retried this with Apple Books Version 5.2 (5800.52) on macOS Ventura. If you replace `:imagesdir: ./images` with `:imagesdir: images`, things Just Work. I'm closing this issue as "fixed on reader app side", but feel free to comment in case I messed up something.
