### ISSUE TITLE
inline / long lines leads to no gap between line numbers and source code

### ISSUE THREAD

**Issue by meonkeys** [asciidoctor/asciidoctor-epub3#451]
I'm generating an EPUB with source code blocks. The line numbers are *very* close to the first characters in the lines of source code. Is there some way to increase this column width/gap? My PDF and HTML outputs look great.

Example input:
```
[%linenums,yaml]
----
version: '3.6'

services:
  api:
```

output:

![Screenshot from 2024-01-05 12-43-43](https://github.com/asciidoctor/asciidoctor-epub3/assets/50639/a3d339a2-aa51-48dd-8233-a9219dfad68d)

(using Calibre E-Book viewer on Ubuntu desktop)

other info:
```
Asciidoctor EPUB3 1.5.1 using Asciidoctor 2.0.20 [https://asciidoctor.org]
Runtime Environment (ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

One workaround I've found is to add a space at the beginning of each line of source code. Not the most elegant, obviously.

Perhaps it is also relevant that I have this document attribute set: `:pygments-linenums-mode: inline`. EPUB *needs* that attribute or the line numbers don't line up (again, I got me some long lines). I'm happy to provide a full standalone working repro if that's helpful.

**Comment by slonopotamus** [comment]
I added some initial fixes. Styling still differs _a lot_ when `:pygments-linenums-mode: inline` is enabled (most visible thing is background color change). But at least it doesn't look like a bug anymore.
