### ISSUE TITLE
Clean auto-generated file names for chapters

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-epub3#46]
The auto-generated file names aren't being cleaned. For instance, if there's a single quote in the chapter title, then a single quote ends up in the file name. If a smart quote is in the title, things get even worse because the entry also doesn't display properly in the TOC (the entity is shown instead).

**Comment by mojavelinux** [comment]
The problem with the TOC entry is that the entry is being double escaped in toc.ncx. When the title is:

```
= JHipster's UI Components
```

we're getting the following:

```
<text>JHipster&amp;#8217;s UI components</text>
```

cc @mraible

**Comment by mojavelinux** [comment]
The file name in the epub3 manifest is:

```
OEBPS/jhipster&#8217;s-ui-components.xhtml
```

**Comment by jmMeessen** [comment]
Is there a work around ? I have the same kind of issue (I think) with chapter titles with french accented characters.

**Comment by mojavelinux** [comment]
Yes, you need to explicitly assign an id for the chapter.

```
[[jhipsters-ui-components]]
== JHipster's UI Components
```

This is now covered in the README. See https://github.com/asciidoctor/asciidoctor-epub3#declaring-the-spine

**Comment by jmMeessen** [comment]
it works \o/
It was not obvious to me from the readme that assigning the ID at chapter level would solve my epubcheck errors/warnings.

**Comment by mojavelinux** [comment]
As soon as I pointed you there, I realized that the hint was much too subtle. But I think I didn't go into detail because I really want to just fix the issue :) What I'll do is point to the issue in the README.
