### ISSUE TITLE
After upgrade to 2.0.0, `<em>` and `<strong>` tags no longer work

### ISSUE THREAD

**Issue by georgeraraujo** [asciidoctor/asciidoctor-epub3#461]
Tested on Calibre 7.3.0, Kindle Paperwhite 3 (2015) 7th Gen with firmware 5.16.2.1.1, and Sigil 2.0.2.

I install and run `asciidoctor-epub3` like this:

```
rvm --force gemset delete v200
rvm gemset create v200
rvm gemset use v200

gem install nokogiri -v 1.15.5
NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install asciidoctor
NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install asciidoctor-epub3 -v 2.0.0

asciidoctor-epub3 -o v200.epub mwe.adoc
```

The input file `mwe.adoc` and the output follow:

```asciidoc
= Book Title
Author Name
:doctype: book
:imagesdir: images
//...and so on

== Chapter One

Some _interesting_ *text* here.
```

![image](https://github.com/asciidoctor/asciidoctor-epub3/assets/4930759/a76e6279-bfbc-4de3-b678-a88b38634294)

![image](https://github.com/asciidoctor/asciidoctor-epub3/assets/4930759/84e49c43-215a-4dd4-b086-899b4ed482c1)

Whereas on 1.5.1, the tags work. I install and run like this:

```
rvm --force gemset delete v151
rvm gemset create v151
rvm gemset use v151

gem install nokogiri -v 1.15.5
NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install asciidoctor
NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install asciidoctor-epub3 -v 1.5.1

asciidoctor-epub3 -o v151.epub mwe.adoc
```

The output follows:

![image](https://github.com/asciidoctor/asciidoctor-epub3/assets/4930759/9f535dc6-3d01-48fe-8fd4-ca1cdea22a2e)

![image](https://github.com/asciidoctor/asciidoctor-epub3/assets/4930759/c3f9c9cc-b3fc-450d-9166-f27b80481774)

**Comment by slonopotamus** [comment]
Thanks for the report, fixed in just-released Asciidoctor EPUB3 v2.0.1
