### ISSUE TITLE
Callout list items with nested lists fail to render the nested list.

### ISSUE THREAD

**Issue by someth2say** [asciidoctor/asciidoctor-epub3#463]
A simple reproducer:
```
<.> Callout with list
* List Item 1
```
It was expected to be rendered as the HTML output:
<img width="201" alt="image" src="https://github.com/asciidoctor/asciidoctor-epub3/assets/13310156/2910ca2a-c03a-491b-b0c4-23b3c3415bf7">
But the ePub output does not include the nested list:
<img width="201" alt="image" src="https://github.com/asciidoctor/asciidoctor-epub3/assets/13310156/3c3bbc7d-0f2b-4012-819e-553338c9d26b">

Tested with Calibre and epub.js

For the record, the XHTML included in the ePub file does not contain the nested list:
```
<div class="callout-list">
<ol>
<li><i class="conum" data-value="1">①</i> Callout with list</li>
</ol>
</div>
```

**Comment by mojavelinux** [comment]
The EPUB3 converter was originally developed before support was added for blocks (including lists) attached to callout list items. This feature was added to Asciidoctor core in 1.5.6. See asciidoctor/asciidoctor#1478.
