### ISSUE TITLE
Code in pre elements doesn't wrap

### ISSUE THREAD

**Issue by laxika** [asciidoctor/asciidoctor-epub3#467]
Sometimes I have very long code lines (like when listing startup parameters, etc). The EPUB plugin creates `<pre>` tags for code which is fine and required. However, I think the following CSS properties should be set for these pre tags to make them wrap, otherwise the text flows outside the readers I tested.

```
white-space: pre-wrap;
word-wrap: break-word;
```
![badcode](https://github.com/asciidoctor/asciidoctor-epub3/assets/1862574/652f7857-9cd5-4084-8679-47be228c534f)

**Comment by slonopotamus** [comment]
Hmm... But we [have](https://github.com/asciidoctor/asciidoctor-epub3/blob/v2.1.0/data/styles/epub3.scss#L814) `white-space: pre-wrap`... My  CSS knowledge is not that great, need to investigate why it doesn't want to wrap.

**Comment by laxika** [comment]
Thanks a lot for the information. I think the reason why I get so poor results is because the CSS doesn't load. I use a super old epub reader. Trying to view the book on my Android reader works well. Closing this because the problem is probably on my side. Sorry for the time wasted on your end. :/
