### ISSUE TITLE
Crash on @xrefs_seen nil

### ISSUE THREAD

**Issue by Ioan-Cristian** [asciidoctor/asciidoctor-epub3#472]
Hello!

I'm trying to build EPUB documentation for [RISC-V ISA](https://github.com/riscv/riscv-isa-manual). When I generate the EPUB version of *riscv-unprivileged.adoc*, I get the following [error](https://pastebin.com/vJrny3r9). I couldn't reproduce the bug on a sample file.

[Here](https://codeberg.org/Ioan-Cristian/riscv-isa-manual) is the modified GitHub repository that supports EPUB. To reproduce the error, run:

```bash
cd build
make unpriv-epub
```

Is this a bug in `asciidoctor-epub3`? Is the RISC-V manual ill-formatted?

Thank you for your help!

**Comment by slonopotamus** [comment]
Ouch. I always believed that the first thing that would be passed to `convert` would be `Document`.

This is a bug in asciidoctor-epub3.
