### ISSUE TITLE
weird tag in minimal book

### ISSUE THREAD

**Issue by rmschindler** [asciidoctor/asciidoctor-epub3#482]
I created a rather minimal book, here it is in its entirety:

````
= the book title

== chapter 1

this is chapter 1

== chapter 2

and this, chapter 2

== chapter 3

and this one, muchacho, is chapter 3
````

when I run `asciidoctor-epub3 -D _book book.adoc`, and open the resulting book in the Books app, this is what I see (notice the weird green tag at the very end) :

<img width="612" alt="Screenshot 2024-06-19 at 13 48 10" src="https://github.com/asciidoctor/asciidoctor-epub3/assets/17572328/290fcb90-ee56-497f-a9aa-38b00f681e39">

aside: I haven’t looked into the actual epub archive to see what’s going on; I haven’t been able to figure out how to do that yet

**Comment by mojavelinux** [comment]
That tag is intentional. It marks the end of the chapter visually.

**Comment by rmschindler** [comment]
the end of the _last_ chapter? (— as we only see it at the end of chapter 3)

so do I understand correctly that if I made a book with AsciiDoctor-epub, it will have to have this green tag in it?

**Comment by slonopotamus** [comment]
Say `:doctype: book` at document header and this thing will be gone

**Comment by slonopotamus** [comment]
What you actually made with this example is not a _book_.

**Comment by rmschindler** [comment]
I see . I added `:doctype: book` and the weird tag went away . thank you

**Comment by mojavelinux** [comment]
Yep, it should only be for an article. It's not a weird tag. It's a typical
end of article mark that you see in a lot of journal publications. But I do
recognize that it's not suitable for all users and perhaps should be
something that's configurable.
