### ISSUE TITLE
kf8 Export doesn't display TIP, NOT or IMPORTANT images

### ISSUE THREAD

**Issue by wintermeyer** [asciidoctor/asciidoctor-epub3#50]
I use asciidoctor-epub3 to export to kf8 for Kindle. The result looks beautiful but is misses the little images next to TIP, NOTE and IMPORTANT. I guess the files are missing or there is an error in the CSS.

I use this command to render the kf8 version:

    asciidoctor-epub3 -D output -a ebook-format=kf8 book.adoc

**Comment by mojavelinux** [comment]
Are you enabling font-based icons?

In your document header:

```
:icons: font
```

or the cli:

```
asciidoctor-epub3 -D output -a ebook-format=kf8 -a icons=font book.adoc
```

Icons are not on by default.

**Comment by mojavelinux** [comment]
Can you tell me which viewer you are using?

**Comment by mojavelinux** [comment]
I'm pretty confident this is now resolved with the last master (if it wasn't just a configuration issue). We've extensively tested the sample book on Kindles, the Kindle Previewer and KDP and everything is looking solid on devices that support the KF8 format.
