### ISSUE TITLE
kf8 Export has a problem with images

### ISSUE THREAD

**Issue by wintermeyer** [asciidoctor/asciidoctor-epub3#52]
Every time I try to convert an AsciiDoc document to mobi I get the following error:

```
Warnung(prcgen):W14010: Mediendatei nicht gefunden   /var/folders/3g/f_fnqw5x7gn6b7nvvky8rbhh0000gn/T/mobi-vYctXi/OEBPS/images/screenshots/chapter05/products_index.jpg
```

Converting the same document to HTML with `asciidoctor` works fine.

**Comment by mojavelinux** [comment]
This is probably related to the issue that @mraible was having. Asciidoctor EPUB3 is currently very picky about where images are placed. If I remember correctly, the `imagesdir` attribute has to be set to `images`. See #22.

**Comment by mojavelinux** [comment]
I was able to verify that this problem was resolved by moving the images to the images folder in the book source. Image target paths are resolved relative to this directory.
