### ISSUE TITLE
Disable avatars?

### ISSUE THREAD

**Issue by and3k** [asciidoctor/asciidoctor-epub3#53]
Hi,

I’m using asciidoctor-epub3 to create a novel-style EPUB, and there I would like to keep it more simple and don’t use avatars. Is this possible?

Thanks. Keep up the great work!
Bela

**Comment by mojavelinux** [comment]
The avatars are actually a hold out from the original use of Asciidoctor EPUB3 to generate a magazine publication and really should be removed. Let's make that the focus of this issue. They can (and should) be added back in using an extension anyway.

In the meantime, you can disable them using CSS. Something like:

```css
.chapter-header p.byline {
  display: none;
}
```

In general, I think we need a more generic chapter header style in the default theme.

We may still want to leave in the logic for the packager to bundle the author avatars in case they are needed / wanted somewhere. We just shouldn't include them by in the header by default.

Here's the logic that needs to get removed: https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/converter.rb#L187

**Comment by and3k** [comment]
:+1: Thanks

**Comment by neontapir** [comment]
In my use case, I wanted to keep the `chapter-header` title but not the avatar or the author (it's a book, so it's me every time). Modifying the included `data\styles\epub3.css` file in this way worked for me:

```css
p.byline {
  display: none;
}
```

In general, I'd like to see more documented guidance in this area. Right now, it's hard to tell what CSS classes control what without experimenting.

**Comment by mojavelinux** [comment]
I'd say these styles around the header are largely subject to change. As you can tell, they were created with a specific branding in mind. We need to move towards something more generic in the default stylesheet, likely dropping the avatar outright. It's just a hold out from the original import of the code.

**Comment by mojavelinux** [comment]
Avatars and headshots will only be included if you set the `publication-type` attribute to a value other than book. The assumption is that collections need author attribute per chapter, but books do not.

**Comment by mojavelinux** [comment]
I'm also thinking about inverting the colors for the chapter title by default (gray on white). I'll handle that in a separate issue.
