### ISSUE TITLE
can not convert cell with style

### ISSUE THREAD

**Issue by flyisland** [asciidoctor/asciidoctor-epub3#69]
for example, asciidoctor-epub3 will convert below source 

---
[cols="2,3,5a"]
|===
|Name |Group |Description

|Firefox
|Web Browser
|Mozilla Firefox is an open-source web browser.
It's designed for:

* standards compliance,
* performance and
* portability.

|Ruby
|Programming Language
|A programmer's best friend.

...
|===

---

into 

name | group | Description
---|---|---
Firefox | Web Browser  |
Ruby | Programming Language |

**Comment by mojavelinux** [comment]
Oops, looks like we forgot to implement the embedded handler. PR sent.
