### ISSUE TITLE
avatars image not found!

### ISSUE THREAD

**Issue by flyisland** [asciidoctor/asciidoctor-epub3#71]
there is `<img src="images/avatars/default.jpg"/>` in each chapter, but there is no such jpg file under the `images` folder inside the generated epub file. I have to delete this `<img>` tag manually in each chapter file to avoid the ugly `X` icon since the reader can not find the image file.

btw, there are two jpg files, `default.jpg` and `default0001.jpg` in the `image` folder, which are not used by any chapter, why include them in the epub file?

**Comment by mojavelinux** [comment]
When using Asciidoctor EPUB3 at the moment, you have to set:

```
:imagesdir: images
```

Otherwise, the paths to the built-in avatars will be incorrect (issue #2).

As for removing the avatars, see #53.

To make the intent clear, we do plan on making the avatars an optional feature. I think that is covered by #53.

**Comment by flyisland** [comment]
got it
