### ISSUE TITLE
Admonition icons incorrect (bitcoin currency for TIP)

### ISSUE THREAD

**Issue by mfitzp** [asciidoctor/asciidoctor-epub3#72]
The icons used for admonitions don't match the output for PDF or HTML generated documents. For example, the TIP admonition should be a lightbulb but shows up as a bitcoin currency marker. This can be seen in the README for the repo, e.g.

![Tip admonition](https://github.com/asciidoctor/asciidoctor-epub3/raw/master/data/samples/images/screenshots/figure-admonition.png)

I see that in the standard `epub3.css` styles the Bitcoin icon is specified for the tip admonition:

```
aside.tip::before {
  /*content: "\f069";*/ /* fa-asterisk */
  /*content: "\f0d6";*/ /* fa-money */
  content: "\f15a"; /* fa-bitcoin */
  color: #57AD68; /* 87,173,104 */
}
```

Is this intentional, or a bug (PRs welcome?)

**Comment by mojavelinux** [comment]
This was an intentional design choice (aka "it's not a bug, it's a (design) feature").

A similar question came up on the list (http://discuss.asciidoctor.org/epub-and-mobi-version-show-wrong-admonition-icon-td4526.html). I gave a pointer about how to override.

I choose the bitcoin icon for tip instead of the lightbulb so it matches the EPUB3 styling better (it's flatter). The reason for the choice is that it represents a "tip" in the closest thing to a universal/digital currency.

**Comment by mojavelinux** [comment]
I think it's reasonable to find a way to override admonition icons in a less laborious way. If you have ideas for that, I'm definitely eager to hear. We can manipulate the stylesheet as it is being put into the epub archive.

**Comment by mfitzp** [comment]
Oh I get it :) didn't make the connection bitcoin to tip. I would prefer consistency across the outputs, but if it is configurable it sidesteps that nicely.

I've been experimenting with some custom styles for both the HTML and epub3 outputs and I think the 'ideal' situation would be to be able to supply 'extra' CSS to be appended onto the main styles before archiving (or inserting in the HTML).

That would give customisation with minimal duplication — and the only 'cost' is the redundant CSS left in.

**Comment by mojavelinux** [comment]
I agree we need to have a simpler way to add extra CSS. In the html5 backend, we can use docinfo for this. However, for epub3, docinfo is not currently incorporated.

When I created the epub3 and pdf converters, I experimented with deviating from the default Asciidoctor look a bit, trying to explore new ideas & territory. I'm willing to accept that the bitcoin analogy may not be intuitive enough. We could go back to the lightbulb (lightbulb-o) or perhaps the star (star-o).

**Comment by allenan** [comment]
Glad I checked here, I also thought the bitcoin icon was a bug. While it may not fit with the epub aesthetic as nicely, I think lightbulb is the most universal icon for 'tip'. In the meantime, I'll look into overriding the style.

**Comment by PrimaryFeather** [comment]
I just wanted to chime in here to let you know I also thought that icon was used by accident. I think the standard light bulb would be a better choice — if nothing else, for consistency with what's done in the default styles of the PDF and HTML output.

**Comment by mojavelinux** [comment]
If someone wants to send a PR for this, I'm happy to change it.

**Comment by mojavelinux** [comment]
The tip icon is now a lightbulb.
