### ISSUE TITLE
Send to Kindle breaks encoding

### ISSUE THREAD

**Issue by robertkowalski** [asciidoctor/asciidoctor-epub3#73]
Hi and thank you for your great work on asciidoctor.

I uploaded my book to KDP yesterday. I uploaded the .mobi and tested it afterwards as they allow you to download it after they processed it. Transferred with USB, looked fine.

When I click "look inside book" at http://www.amazon.com/The-CLI-Book-Writing-successful-ebook/dp/B01ED4QWPA?ie=UTF8&*Version*=1&*entries*=0 everything looks good, too.

The encoding gets weird when I click "send free test chapter to kindle":
![img_7772](https://cloud.githubusercontent.com/assets/298166/14587626/318e9d1e-04b6-11e6-937c-37aacdb1afb6.JPG)

You can try it out by getting the free chapter at http://www.amazon.com/The-CLI-Book-Writing-successful-ebook/dp/B01ED4QWPA?ie=UTF8&*Version*=1&*entries*=0 or the corresponding website for your country (this link is US, but they will redirecct you to your contry)

**Comment by mojavelinux** [comment]
The "send free test chapter to kindle" feature is known to have an incredible number of bugs. There is really nothing we can do in Asciidoctor (that I've been able to work out) because this is simply the Kindle software corrupting the EPUB3 file.

**Comment by mojavelinux** [comment]
To be clear, it is breaking the encoding of the document.

**Comment by mojavelinux** [comment]
Here's my theory about this. Whatever Amazon uses for the "send to Kindle" action is an outdated toolchain which severely mangles the archive. Given this is proprietary software, there's nothing we can do about it.

What I recommend is passing the archive to the device using one of two methods:

1. Direct copy to the kindle data folder on the device
    * This is how I test; you can find an example for Android in the following script: https://github.com/asciidoctor/asciidoctor-epub3/blob/master/bin/adb-push-ebook
2. Use Kindle Direct Publishing, but keep the book in draft mode
    * This is a replicate of what users who shop through the Kindle store will experience; see https://kdp.amazon.com/help?topicId=AT1K7B0DRETM0

**Comment by mojavelinux** [comment]
"Send to Kindle" also breaks font-based admonition icons since the toolchain strips the fonts from the archive.

**Comment by mojavelinux** [comment]
I've documented this problem in the README. This is not a problem with the Asciidoctor EPUB3 software and there is nothing we can do to fix it. Therefore, I'm closing this issue.

https://github.com/asciidoctor/asciidoctor-epub3#send-to-kindle

If there are other points you want to see made in the linked section, I'd be happy to add them.
