### ISSUE TITLE
Same image included multiple times fails epubcheck

### ISSUE THREAD

**Issue by handcraftsman** [asciidoctor/asciidoctor-epub3#76]
I used an image (pixel.jpg) several times in a chapter.  When I uploaded the epub file to Leanpub it failed epubcheck with the following error:

```
duplicate resource: OEBPS/images/pixel.jpg
```

Ideally asciidoctor-epub would recognize duplicate image files and assign them the same id.

**Comment by mojavelinux** [comment]
I agree. It's strange that gepub doesn't detect duplicate files (after all, it's the archive manager). I guess we'll need to do it in lieu of that.
