### ISSUE TITLE
cover.xhtml of epub3-file has broken width attribut 

### ISSUE THREAD

**Issue by lafisrap** [asciidoctor/asciidoctor-epub3#78]
> For Asciidoctor-epub3 version:
> Asciidoctor EPUB3 1.5.0.alpha.7.dev using Asciidoctor 1.5.4 [http://asciidoctor.org]
> Runtime Environment (ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
> 

I converted some adoc-Files to epub and the cover didn't appear in two readers (calibre,iBooks). I discovered that the cover.xhtml in the OEBPS folder contains:

```
<body epub:type="cover"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
 26   width="100%" height="100%" viewBox="0 0 height=1600 1600" preserveAspectRatio="xMidYMid meet">
<image width="height=1600" height="1600" xlink:href="images/jacket/cover.jpg"/>
```

Twice: height=1600 instead of a width value. Width was set to 1050 before in the root adoc file:

`:front-cover-image: image:bookcover.jpg[width=1050,height=1600] `

**Comment by mojavelinux** [comment]
This happens because the image macro doesn't support explicit attribute names (it's not yet parsed like a regular inline macro, hence the more strict requirements).

You should define it as follows:

```
:front-cover-image: image:bookcover.jpg[Cover,1050,1600]
```

**Comment by lafisrap** [comment]
Thanks. That did the trick.
