### ISSUE TITLE
minimising output file size

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [asciidoctor/asciidoctor-epub3#80]
Can the completed XHTML and CSS be passed through minify/tidy procedures before creating the archive? Likewise, can fonts be subset instead of embedding the whole thing? Images, too. Epub and KF8 are already small compared to PDF, but it's somewhat impolite to include more than what's needed in the archive.

Should be pretty easy to achieve?

```
for each (stylesdir/*.css)
  cssnano
for each (*.xhtml)
  html-minifier
for each (images/*.png)
  optipng
for each (images/*.jpg)
  imagemagik yada yada
```

**Comment by mojavelinux** [comment]
kindlegen actually does this already, afaik. So this would be more for the native EPUB output. Does seem like a good idea, though.

**Comment by slonopotamus** [comment]
Unlike web stuff, EPUB3 is a compressed format, so gains from compression are not going to be that great. And we have higher penalty for using non-Ruby software because we cannot install it automatically. And I'd say that current book sizes are "good enough".

**Comment by slonopotamus** [comment]
Starting with c39d2159a8c329e2e2179a12c6cd7f4b39898f74, we output css files in compressed form (no comments and redundant newlines).

**Comment by slonopotamus** [comment]
I've tried minimizing HTML using

```ruby

      def postprocess_xhtml content
        if @format == :kf8
          # TODO: convert regular expressions to constants
          content = content
            .gsub(/<img([^>]+) style="width: (\d\d)%;"/, '<img\1 style="width: \2%; height: \2%;"')
            .gsub(/<script type="text\/javascript">.*?<\/script>\n?/m, '')
        end

        doc = Nokogiri::XML.parse(content)
        doc.search('//comment()').remove
        doc.search('//text()[normalize-space()=""]').remove
        result = doc.to_xml(save_with: Nokogiri::XML::Node::SaveOptions::AS_XML)
        result.to_ios
      end
```

But... That resulted in 707KB -> 706KB total size for [git-as-svn](https://github.com/git-as-svn/git-as-svn) doc book and breakage of `<pre>` formatting. I don't think it is worth the effort and CPU cycles.

**Comment by slonopotamus** [comment]
I'd like to claim this issue is resolved.
