### ISSUE TITLE
How to style pygments BW theme to remove red error borders

### ISSUE THREAD

**Issue by jawache** [asciidoctor/asciidoctor-epub3#81]
I'm using pygments, it doesn't quite support the idea of typescript yet and inline HTML and draws these red borders around my code snippets.

https://www.dropbox.com/s/3hixxbxfg91jx8w/Screenshot%202017-01-19%2023.40.36.png?dl=0

In the HTML version of asciidoctor i just added the css to ignore .tok-err but i'm not sure what to set to get it working in the epub version (i've set the same CSS and it's not working)

`
.tok-err {
  border: none !important;
}
`

I've tried viewing the epub in calibri but in the HTML there the red border is already inlined in the HTML and therefore it's hard to figure out what classes to use to style?

Any hints ideas? Even if it's how to view an EPUB in some prebuilt form where I can see the classes?

**Comment by mojavelinux** [comment]
The red border indicates that there is an error in highlighting...technically you should be able to correct all those before the final version of your publication.

If you cannot, you need to provide your own Pygments theme using your own Pygments installation. That's where the styles are coming from. It works the same in all Asciidoctor converters (when you are inlining the styles, as we do in the EPUB3 converter).

To use your own installation of Pygments, which is where you can define or override the theme, follow this guide:

http://asciidoctor.org/docs/user-manual/#using-a-custom-pygments-installation

**Comment by mojavelinux** [comment]
In addition to those instructions, I did the following:

* copied pygments/styles/bw.py to pygments/styles/bw-override.py (in the Pygments install)
* renamed class in pygments/styles/bw-override.py from BlackWhiteStyle to BlackWhiteOverrideStyle
* added the following entry to the STYLE_MAP in pygments/styles/__init__.py
    ```python
    'bw-override': 'bw-override::BlackWhiteOverrideStyle',
    ```
* enabled the override script and enabled the pygments-style attribute when calling asciidoctor-epub3
    ```
    asciidoctor-epub3 -r ./custom-pygments.rb -a pygments-style=bw-override book.adoc
    ```

I'm not sure how else to provide a custom style to Pygments. We don't have direct access to Python code, so we have to hack Pygments directly. If you know of another way, I could certainly help get it working. For now, this is the only way I know how.

**Comment by mojavelinux** [comment]
The other approach is to set the pygments-css attribute to class. However, then you have to use a custom epub3.css stylesheet and add the rules to it, as described in https://github.com/asciidoctor/asciidoctor-epub3#about-the-theme.

**Comment by slonopotamus** [comment]
Since we're going to drop pygments.rb (#262), I'm closing this as WONTFIX.
