### ISSUE TITLE
Make byline optional

### ISSUE THREAD

**Issue by thjanssen** [asciidoctor/asciidoctor-epub3#86]
I'm writing a software development book and don't need the byline at the top of each chapter. Hiding it with the following css code doesn't seem to work on all readers. It would be great, if the byline would be optional so that it doesn't get generated, if I don't need it.

```
.chapter-header p.byline {
  display: none;
}
```

**Comment by mojavelinux** [comment]
I agree the byline should be optional for books (as it doesn't make sense to repeat the author every chapter). We need some way to express (or autodetect) this.

It would also be helpful to provide information in the README about how to disable the byline using CSS. It requires adding the CSS rule to the proper place so it's picked up by all readers. My guess is that it's not being added to the right stylesheet.

**Comment by mojavelinux** [comment]
I checked the reader in question (Prestigio) and it's one of those readers that only honors a very limited set of CSS rules. For these readers, none of the HTML included in the book can be hidden. This is just a fact of life in digital publishing. Readers are all over the place when it comes to what CSS they allow.

Therefore, it makes total sense to be able to suppress this information and not just rely on CSS.

**Comment by mojavelinux** [comment]
It feels like the best way to express this is through the attribute `publication-type`. When `publication-type` has the value "book" (which is the default), then we assume that we don't want bylines per chapter.

Here are the values I'm thinking for this attribute:

* book
* journal (or magazine)
* article (a single entry unlike a journal or magazine)

For now, we'll exclude the byline when the publication type is book.

**Comment by mojavelinux** [comment]
Another idea is to see if the chapter specifies it's own author. If so, we'd use the byline. (but still not for a book).

**Comment by mojavelinux** [comment]
I'm going to go with the publication-type logic for now (which requires no action for authors of books). We can change this logic in the future if we find a better way to do it.
