### ISSUE TITLE
Implement converter for video and audio blocks

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor-epub3#9]
Here is one of the lines that didn't render properly in epub3:

```
.Video: random walk
video::random2a.m4v[width=400, align=center]
```

This is from `01.ad` in the [processing-book repo](https://github.com/jxxcarlson/processing-book).  The video does render properly with `asciidoctor 1.5`.  I used iBooks as the epub3 reader.  Everything (text, images) looked OK with except the video.

**Comment by edusantana** [comment]
This page provide the `video` tag for epub3 that can be tested with Android and Google play books:

https://support.google.com/books/partner/answer/3316879

**Comment by mojavelinux** [comment]
I'm happy to report that Gitden now supports audio and video, so I finally have an e-book reader to test it on. We can do this now!

**Comment by slonopotamus** [comment]
Madness. Calibre only shows video only if *both* webm and mp4 files are provided.

**Comment by slonopotamus** [comment]
WRT video: Calibre only supports WEBM. Google Books claims to support WEBM + MP4 (H264). I would not be surprised if there are readers that only support MP4. 

However, Asciidoctor `video` macro only allows to specify one file. We possibly need to do some trickery and look if there are files with different formats lying next to specified file and grab them also.
